### ISSUE TITLE
Are there any breaking changes updating to ng-quill 3.x?

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ng-quill#101]

**Comment by KillerCodeMonkey** [comment]
yep:
if you set a default conf via config provider you need to pass a config object instead of multiple params.

a selection changed callback is added and on-content-changed has additional data, now:
`on-content-changed="myCallback(editor, html, text, delta, oldDelta, source)"`

**Comment by jziggas** [comment]
Alright cool. Thanks!
