### ISSUE TITLE
Broken Build since update

### ISSUE THREAD

**Issue by CHR15-** [KillerCodeMonkey/ng-quill#104]
Hi,

I'm having issues building the ng-quill file and has started occurring since the change from 2.3.0 -> 3.0.1

This error pops up when you concat/uglify files and theres a missing semicolon between files. 

Same issue as here
http://stackoverflow.com/questions/23370269/jquery-autosize-plugin-error-intermediate-value-is-not-a-function

&& 

https://github.com/feross/standard/issues/373

![screen shot 2017-03-24 at 10 54 32](https://cloud.githubusercontent.com/assets/5793128/24291328/6c06bc52-1080-11e7-8a32-fcfb7a33713b.png)

![screen shot 2017-03-24 at 10 54 40](https://cloud.githubusercontent.com/assets/5793128/24291332/6f1c5c4e-1080-11e7-87ee-67caef8dd16e.png)

**Comment by KillerCodeMonkey** [comment]
Thank for letting me know. 

I added a little step in my build process, that adds a trailing ; at the end of the not minified version of ng-quill in the dist folder:

https://github.com/KillerCodeMonkey/ng-quill/commit/4c17027e5ab4a022055b8b603cbd5888ec0ffc58

Let me know of this would solve your problem.

**Comment by CHR15-** [comment]
Thanks will look to test today/tomorrow

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by CHR15-** [comment]
Apologies, haven't got round to this but will be def doing so tomorrow!

**Comment by KillerCodeMonkey** [comment]
well that was a fast one 🚤 !

**Comment by CHR15-** [comment]
https://github.com/manosim/gitify 👍

**Comment by iarroyo5** [comment]
@KillerCodeMonkey I'm working in the same team as @CHR15- . We've checked your update and it fixes the issue. 

Thanks.

**Comment by KillerCodeMonkey** [comment]
closed with https://github.com/KillerCodeMonkey/ng-quill/commit/a2b511449e850c09287a46f5babddb3f2b35e6be
