### ISSUE TITLE
Creating a custom imageHandler

### ISSUE THREAD

**Issue by relentless-coder** [KillerCodeMonkey/ng-quill#106]
Hi,

Could you please explain me that where do I plug my custom image handler?? According to Quill's documentation, it can be easily done in the options. However, in ng-quill the options are set in config block, so I have no idea how do I link my custom image handler on my controller to the imageHandler option.

**Comment by KillerCodeMonkey** [comment]
eeehhm i only found https://github.com/quilljs/quill/pull/995 but nothing in the official documentation.

If you want to overwrite the toolbar handler check out the last replies on the quill issue, where you add your handler after editor creation or you can pass handlers to the modules property of ng-quill (https://quilljs.com/docs/modules/toolbar/)

**Comment by KillerCodeMonkey** [comment]
any updates?
