### ISSUE TITLE
[Parchment] Invalid definition on IE11

### ISSUE THREAD

**Issue by sentient06** [KillerCodeMonkey/ng-quill#107]
Hello, I am using NPM and grunt:

    "dependencies": {
        "angular": "^1.5.8",
        // etc
        "quill": "^1.2.2",
        "ng-quill": "^3.0.0",
        "ngclipboard": "^1.1.1"
    }

My module looks like this:

    var ngApp = angular.module('appName', [
        // bunch of dependencies
        'ngQuill'
    ], function($interpolateProvider) {
        // ...
    });

Works perfectly fine on Chrome and Firefox for Mac OS X and Windows.

Yet it fails on IE 11:

    SCRIPT5022: [Parchment] Invalid definition
    SCRIPT5022: [$injector:modulerr] Failed to instantiate module appName due to:
    Error: [$injector:modulerr] Failed to instantiate module ngQuill due to:
    Error: [$injector:nomod] Module 'ngQuill' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.5.3/$injector/nomod?p0=ngQuill at Anonymous function (https://yadyadayada/assets/build/js/lib.c9b9d34d.js:12326:11)
    // etc etc
    SCRIPT256: This command is not supported.

If this a Quill issue?

My Grunt file adds Quill to a library file:

        quill: {
            src: [
                '<%= paths.build.js %>/lib.js',
                '<%= paths.npm %>/quill/dist/quill.min.js',
                '<%= paths.npm %>/ng-quill/dist/ng-quill.min.js'
            ],
            dest: '<%= paths.build.js %>/lib.js'
        }

What puzzles me is that only IE11 fails, which makes me think something fails to add backwards compatibility. Any ideas?

**Comment by KillerCodeMonkey** [comment]
strange maybe something wrong with the loading order?
ngQuill should be loaded before your angular app.

"sadly" i do not own a windows pc with IE.

Could you test the example of ng-quill in the repo in IE11?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by sentient06** [comment]
Hello, the issue had to do with minification. You may consider the issue closed. Thanks!

**Comment by KillerCodeMonkey** [comment]
no probs and thanks for the (late :D) response.

**Comment by hilmarh** [comment]
Since this is one of the few results for this error on Google, I'd like to point out that one rare possibility for this error on IE11 is the `x-ua-compatible` header!

`<meta http-equiv="x-ua-compatible" content="IE=10">`

Should be set to

`<meta http-equiv="x-ua-compatible" content="IE=edge">`
