### ISSUE TITLE
Validation Callback Functionality?

### ISSUE THREAD

**Issue by Pickra** [KillerCodeMonkey/ng-quill#11]
It would be great if ng-quill could:
- specify max length.
- handle defining a callback function to deal with validation in the config object.
- have an attribute that handles the above.

I went over the documentation, didn't see a way to do this.
Am I missing something?

**Comment by KillerCodeMonkey** [comment]
Nope, this is actually not possible.
But a good task for improvement.

Thanks i hope i have the time to get into this feature.

In any other cases feel free to build it your own and make a pull-request.

**Comment by KillerCodeMonkey** [comment]
Does any body will fix this in the old 0.20.1 version?
if not i close this issues and you can try ng-quill 2.0.1 or if you are using angular2 the total new ng2-quill component.
