### ISSUE TITLE
how to Building a Custom Module?

### ISSUE THREAD

**Issue by zhougonglai** [KillerCodeMonkey/ng-quill#111]
i need add a music button.
i can't find How to add a format use the ng-quill!?

**Comment by KillerCodeMonkey** [comment]
like you would do it with plain quilljs ;)
https://quilljs.com/guides/building-a-custom-module/

or configure your formats:
https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting

register your module/format on the global Quill object and after that you can use it ;)

You can configure your toolbar through `modules` input of `ng-quill-editor` component. There you can pass an javascript object with the configuration of your toolbar or other modules.

Or you can build up your own toolbar directly with html-code with the `ng-quill-toolbar` component 
https://github.com/KillerCodeMonkey/ng-quill#usage

An example of that you can find here: https://github.com/KillerCodeMonkey/ng-quill/blob/develop/demo.html

**Comment by zhougonglai** [comment]
tanks!~
