### ISSUE TITLE
Toolbar doesn't inherit other properties

### ISSUE THREAD

**Issue by jmsfilipe** [KillerCodeMonkey/ng-quill#112]
Handlers, for instance, are ignored.

I found this issue when updating from version 2.2.5.
The problem starts in version 2.3.0.

on line 163
```
// set toolbar to custom one
if ($transclude.isSlotFilled('toolbar')) {
  config.modules.toolbar = container.find('ng-quill-toolbar').children()[0];
}
```
If I attempt to add a custom handler, that would be added to config.modules.toolbar.handlers.
And it would be ignored after that assignment.

I think the solution would be to extend the object, instead of replacing it

This will likely solve what I think is #106 problem

**Comment by KillerCodeMonkey** [comment]
you are not forced to use the ng-quill-toolbar component. you can simply stuck with config your toolbar as a javascript object.

Or add you toolbar handlers afterwards:

```
// Handlers can also be added post initialization
var toolbar = quill.getModule('toolbar');
toolbar.addHandler('image', showImageUI);
```

So listen on the `onEditorCreated` output were you get the editor instance as the `$event` data.

Also described in the quill documentation:
https://quilljs.com/docs/modules/toolbar/
