### ISSUE TITLE
How correct register new custom module?

### ISSUE THREAD

**Issue by andriinuts** [KillerCodeMonkey/ng-quill#113]
Hey, I'm trying to register: https://www.npmjs.com/package/quill-image-resize-module
But unfortunately I cant find correct way for make Quill.register() work.
How I can correctly connect new module to ng-quill?

**Comment by KillerCodeMonkey** [comment]
I do not know this module and how it works.

But in general, you can access Quill after you included it in your index.html head area via:

```
Quill 

window.Quill
```

The image resize addon should provide a .js file which you also can include. After that ImageResize is globally available via `ImageResize` or `window.ImageResize`

Then follow the `Quill.register` step.
Here you can find an example with simple ES5 Script:
https://plnkr.co/edit/gq708AOrSBOWSlHcFslG?p=preview

**Comment by andriinuts** [comment]
I get this error: 
![image](https://cloud.githubusercontent.com/assets/3611521/25887245/ebc99d2a-3569-11e7-9f75-4e9fa037f24e.png)

**Comment by KillerCodeMonkey** [comment]
show me some source code, pls

**Comment by KillerCodeMonkey** [comment]
@andriinuts i checked it out --> this issues has something todo with latest quill versions i think. When i try it with quilljs 1.0.0-beta.3 or some other beta version it seems som how to work with grammarly.

Since the rc releases it does not work anymore.

**Comment by KillerCodeMonkey** [comment]
I will not build this for you ;)

But an example is here:
https://quilljs.com/guides/building-a-custom-module

how you override toolbar handlers, check this:
https://quilljs.com/docs/modules/toolbar/

And all in all, you should ask in the QuillJS repository and try everything in a native JS + QuillJS environment. And if you get everything working there --> put it in the angular context ;)

**Comment by zhougonglai** [comment]
how about add the imageHandler to the config?
http://codepen.io/jackmu95/pen/EgBKZr

**Comment by KillerCodeMonkey** [comment]
yeah, this is how you can add you own custom handlers ;). But this has nothing to do with the original issue...

**Comment by KillerCodeMonkey** [comment]
@andriinuts any updates or details?

**Comment by pierresh** [comment]
I am trying to import that module as well, but I cannot make it... Has someone managed to register that module ? ^^

**Comment by KillerCodeMonkey** [comment]
show us some code ;)

**Comment by KillerCodeMonkey** [comment]
in general load image resize module after quill in the oldschool way.

or if you are using modules, then import quill, import image resize module + register the module with `Quill.register`

Like it is described here:
https://github.com/kensnyder/quill-image-resize-module#usage

**Comment by pierresh** [comment]
I tried to do like this

```
app.constant('NG_QUILL_CONFIG', {
	modules: {
		ImageResize: {}
	}
})

app.config([
	'ngQuillConfigProvider',
	'NG_QUILL_CONFIG',

	function (ngQuillConfigProvider, NG_QUILL_CONFIG) {
		ngQuillConfigProvider.set(NG_QUILL_CONFIG)
	}
])
```

But I get the following errors
<img width="650" alt="WeChat216744f5f376de7eb53b2db4673aea37" src="https://user-images.githubusercontent.com/7520095/59184042-d0c2d080-8b9f-11e9-9be3-e83456faa685.png">



I also tried to register this module in my controller
````
this.editorCreated = function(o) {
	manual.editor = o;

	manual.editor.getModule('toolbar').addHandler('image', () => {
		selectLocalImage();
	});
	manual.editor.register('modules/imageResize', ImageResize);
}
````

I get that error message
<img width="683" alt="WeChat2b38fb7d9db927854302c2e43ff5b4a8" src="https://user-images.githubusercontent.com/7520095/59184242-4890fb00-8ba0-11e9-80d1-73daf8a6a89d.png">

**Comment by KillerCodeMonkey** [comment]
yeah because you have to register the used modules before creating your editor.

Just add quill and image-resize scripts to you index.html before loading your angular app, or make sure you have registered image resize before you are creating your editor instances.

If you are using Quill as global, just load the script of image resize after quilljs script:
like in the image resize demo code:
https://github.com/kensnyder/quill-image-resize-module/blob/master/demo/index.html#L5
Because image resize registers itself if a global quill instance is found:
https://github.com/kensnyder/quill-image-resize-module/blob/master/src/ImageResize.js#L199

If you are using JS modules just import quill and import ImageResize and use the way described in the readme.

https://github.com/kensnyder/quill-image-resize-module#webpackes6

And after that you can initialise a quill editor with imageResize as modules ;)

**Comment by pierresh** [comment]
Alright, I changed the order of import as follow

```html
<script src='./plugins/quill/quill.min.js'></script>
<script src='./plugins/quill/image-resize.min.js'></script>
<script src='./plugins/quill/ng-quill.min.js'></script>
<script src='./js/app.js'></script>
```

I also added these lines just before creating the angularjs app
```js
if (window.Quill) {
    window.Quill.register('modules/imageResize', ImageResize);
}
```

Now I can see that imageResize is taken in account in the console but the picture still cannot be resized and the previous error message still appear
<img width="637" alt="WeChat7d6ea8fe3c680c0c7c418c40f8675d23" src="https://user-images.githubusercontent.com/7520095/59185824-fbaf2380-8ba3-11e9-8ca8-b8a83ce2f0f4.png">

**Comment by KillerCodeMonkey** [comment]
Okay You do Not Need to Register it of You own, If You load IT via scipt
Tag.

That is why You get the warning (overwriting Image resize..).

And it should be "imageResize" Not "ImageResize" i think.

Pierre <notifications@github.com> schrieb am Mo., 10. Juni 2019, 11:21:

**Comment by snake-py** [comment]
Hey guys, similar problem here, although it is quite a time ago the last one was active here, I figured someone might still come across my post.

So this is within laravel:
![image](https://user-images.githubusercontent.com/59285387/78814609-2b4ed800-79cf-11ea-95d1-f2a9bed91c4a.png)

an I get that I have not correctly registered the module. But when I put inline into my html it won't work either. The Quill documentation is not showing the issue. I actually assume that something with my js compiling is wrong? I really don't know, though.

**Comment by pierresh** [comment]
Sorry, I forgot how I fixed, I just remember it was a bit tricky. Here is below all my code about ng-quill, I hope it will be useful for you, good luck!

```js
let Block = Quill.import('blots/block');

// Create a custom blot for Javascript
class JsBlot extends Block {
  static create(url) {
    let node = super.create();
    // Attribute for output HTML
    node.setAttribute('class', 'ql-syntax lang-javascript');
    return node;
  }
}

JsBlot.blotName = 'js';
// Class to look for when parsing your input HTML
JsBlot.className = 'js';
// Tag to look for when parsing your input HTML
JsBlot.tagName = 'pre';
// Register your custom blot with quill.
Quill.register(JsBlot);

// Create another custom blot for Clojure
class CljBlot extends Block {
  static create(url) {
    let node = super.create();
    node.setAttribute('class', 'ql-syntax lang-clojure');
    return node;
  }
}
CljBlot.blotName = 'clj';
CljBlot.className = 'clj';
CljBlot.tagName = 'pre';
Quill.register(CljBlot);


(function(){
	angular.module('my_app', ['ngQuill', ....])
		.controller('MainMenuController', function(TestAuth, $location, $scope){

		})
		.constant('NG_QUILL_CONFIG', {
			  modules: {
			  	imageResize: {},
			  	imageDrop: true
			}
		})

		.config([
			'ngQuillConfigProvider',
			'NG_QUILL_CONFIG',

			function (ngQuillConfigProvider, NG_QUILL_CONFIG) {
				ngQuillConfigProvider.set(NG_QUILL_CONFIG)
			}
		])
```

**Comment by snake-py** [comment]
@pierresh 
thanks I am not working with any js frontend framework like vue angular etc. SO I am not sure. How I can adapt your solution. bur I will work throw it and give it a try. Also, I noticed that something was wrong in my code I posted earlier. 

```
var Quill = require("quill");
const  ImageResize  = require("quill-image-resize");
console.log(ImageResize);

Quill.register("modules/imageResize", ImageResize); // <- changed ImageResize to imageResize

var quill = new Quill("#editor", {
    modules: {
        imageResize: {},
        toolbar: [
            [{ header: [2, 3, false] }],
            ["bold", "italic", "underline", "strike"],
            [{ list: "ordered" }, { list: "bullet" }],
            [{ align: [] }],
            ["image", "link"]
        ]
    },
    theme: "snow"
});
```
this is my current state and I get a differen error message now: 
![image](https://user-images.githubusercontent.com/59285387/78917060-a6c38e80-7a8e-11ea-80a1-f4b8312efe27.png)

**Comment by KillerCodeMonkey** [comment]
as you see your `require` should use `ImageResize.default`. Because it is an es6 module that means it expects that you are using `import ImageResize from 'quill-image-resize'` instead of `require`

If you want to go with require just access the `default` property

`const ImageResize = require('quill-image-resize').default`

**Comment by snake-py** [comment]
Hello @KillerCodeMonkey,
thank you for your quick support. Now it is working properly. 
I leave my code here in case someone runs into the same issue. 

```
const Quill = require("quill");
const ImageResize = require("quill-image-resize").default;
const ImageDrop = require("quill-image-drop-module").ImageDrop;
console.log(ImageResize);
console.log(ImageDrop);

Quill.register({
    "modules/imageResize": ImageResize,
    "modules/imageDrop": ImageDrop
});


const quill = new Quill("#editor", {
    modules: {
        imageResize: {},
        imageDrop: true,
        toolbar: [
            [{ header: [2, 3, false] }],
            ["bold", "italic", "underline", "strike"],
            [{ list: "ordered" }, { list: "bullet" }],
            [{ align: [] }],
            ["image", "link"]
        ]
    },
    theme: "snow"
});
```
