### ISSUE TITLE
Is there any way to insert <FONT> tag?

### ISSUE THREAD

**Issue by gerardolima** [KillerCodeMonkey/ng-quill#117]
I have to reuse HTML generated by legacy client-side editor, but it seems `ng-quill-editor`  does not accept the `<FONT>` tag on its `ng-model`  and uses its inner text, instead.

Is there a way to bypass this limitation?

**Comment by KillerCodeMonkey** [comment]
ng-quill-editor does not limitate anything. The limitation is done by QuillJS the editor behind. The styling for another font family is done by a specific class.

You can check this here: http://killercodemonkey.github.io/ng-quill/demo.html --> watch the JS-Console when you change something.

**Comment by gerardolima** [comment]
hi, @KillerCodeMonkey , thank you very much for your response, but I still can't get it right; could you, please, provide more information about this specific class that I should use and how to register it?

**Comment by KillerCodeMonkey** [comment]
Read here about quilljs and custom fonts:
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors

and a working example here:
https://quilljs.com/playground/#custom-fonts
