### ISSUE TITLE
Cannot set default text in html.

### ISSUE THREAD

**Issue by Igor912** [KillerCodeMonkey/ng-quill#118]
Is it possible to set textData in html between tags? Current approach I choose isn't work.

`<ng-quill-editor ng-model="textData">`
       ` <ng-quill-toolbar>`
           ` <div>`
                `<span class="ql-formats">`
                   `     <button class="ql-bold" ng-attr-title="{{'Bold'}}"></button>`
                   `     <button class="ql-italic" ng-attr-title="{{'Italic'}}"></button>`
            `</div>`
        `</ng-quill-toolbar>`
        `<div>`
            `<h2>Form Display Module</h2>`
        `</div>`
    `</ng-quill-editor>`

**Comment by KillerCodeMonkey** [comment]
nope, you only can pass the html content through the model.

What do you wanna do?
