### ISSUE TITLE
Remove placeholder

### ISSUE THREAD

**Issue by Alplob** [KillerCodeMonkey/ng-quill#119]
Hello,

Thanks a lot for your great plugin! Nevertheless I meet an issue, I could not figure out how to remove the placeholder or making it blank. I tried following options but none of them works..

`<ng-quill-editor placeholder=''>`
`<ng-quill-editor placeholder=' '>`
`<ng-quill-editor placeholder='&nbsp;'>`

Thanks!

**Comment by KillerCodeMonkey** [comment]
updated in the new release --> just pass ' ' as placeholder.
