### ISSUE TITLE
Export the module name for import

### ISSUE THREAD

**Issue by Nargonath** [KillerCodeMonkey/ng-quill#120]
Hello!

Thanks for your great lib and the hard work you've put into it, it makes wonders.

I was just wondering if it would be possible to export the `app.module.name` in the file where the angular *ngQuill* module is created?

It would allow us to import your module as follow:

```javascript
import ngQuill from 'ng-quill';

angular.module('myApp', [ngQuill]);
```

In the current state, it seems that I need to write the name of the module myself as is:

```javascript

import from 'ng-quill';

angular.module('myApp', ['ngQuill']);
```

Is it already possible and it is just me that didn't see it in the doc?

If not, I'll be happy to make a PR to make this change.

Thanks and have a good day.

**Comment by KillerCodeMonkey** [comment]
feel free to make a pull request ;)

**Comment by Nargonath** [comment]
@KillerCodeMonkey Alright, thank you. I'll add it to my TODO list. ;)
