### ISSUE TITLE
Toolbar container

### ISSUE THREAD

**Issue by SamRichards** [KillerCodeMonkey/ng-quill#122]
So from what I can understand from the quillJS documentation, the toolbar can be given a specific container, “It can be configured with a custom container and handlers.“, and I need to detach the location of the editor and the toolbar, by what I could assume would be achieved by giving the toolbar a different container.

From looking at the ng-quill source code I can't see any indication that the toolbar can be appended anywhere except with the container.

So for example if we have 4 text editors on our page, we only want 1 containing div above them all which shows the toolbars when they are they. So the text editors are appended to the container, and the toolbar is appended to the toolbar area.

I may have read the documentation for Quill wrong, or read the source code for ng-quill wrong, so if so, feel free to just say that :)

Thank you in advance!

https://quilljs.com/docs/modules/toolbar/

**Comment by KillerCodeMonkey** [comment]
never tried to add multiple editors to one detached toolbar

But you can pass the same modules and toolbar config to ng-quill like you see under the link: https://quilljs.com/docs/modules/toolbar/

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by SamRichards** [comment]
@KillerCodeMonkey sorry for the confusion, we have a few different editors, and the toolbar will show and hide between which is being edited, it's not multiple editors with one detached toolbar, it's one detached toolbar area where the detached toolbars will reside. It's a little tricky scenario.

I'm going to have a look into this and get back to you, I've been really busy, thanks for the reply!

**Comment by SamRichards** [comment]
Going to close the issue while I investigate.

**Comment by SamRichards** [comment]
So with passing in a container, it does move it (I think?), but it doesn't include any buttons on the toolbar. So I am guessing we are passing in a module for the toolbar and it is overriding everything? and the buttons and container use the same short hand. As we can see in the docs. https://quilljs.com/docs/modules/toolbar/

So we can have for the button options:

```
modules: {
    toolbar: ['bold', 'italic']
  }
```

and for the container:

```
modules: {
    toolbar: '#container'
}
```
or:

```
modules: {
    toolbar: {
      container: '#container'
    }
}
```

But I am getting the toolbar a little bit, but it has no buttons. 

<img width="481" alt="screen shot 2017-07-18 at 17 33 13" src="https://user-images.githubusercontent.com/9961990/28328688-39adcb3c-6bdf-11e7-803e-518457155d30.png">

I am initialising the directive like:

```
<ng-quill-editor
   class="ng-quill-editor ql-editor"
   modules="quillTextModules"
>
</ng-quill-editor>
```

I can't seem to find how to initialise the options and the container in the modules from the quill docs, I see a lot of people do it with HTML, is there an option for it with ng-quill that you know of? Just:

```
modules: {
    toolbar: {
      container: '#container',
      options: ['bold', 'italic']
    }
}
```

**Comment by KillerCodeMonkey** [comment]
maybe your definition of the formats and buttons is wrong?
https://github.com/KillerCodeMonkey/ng-quill/issues/114

sorry i only build this wrapper for angular because i used quill once, so i am not that familiar with the deep insights of quill.

But i think you need to define a nested array with toolbar buttons --> because you can group buttons

And if i understand the sourcecode of quilljs toolbar module correctly --> options is not existing.
They are only added if you do not set a custom container:
https://github.com/quilljs/quill/blob/develop/modules/toolbar.js#L13

First case is, if you only pass a configuration object, second one is if you pass a css selector string and the else case is if you pass an element.

So maybe this is more a quilljs issue than a ngx-quill... sorry. But i advice you to search for an existing issue there or open a new one.

Close this issue again if you agree with it

**Comment by SamRichards** [comment]
Right, @KillerCodeMonkey I've found the solution.

It is a problem inherit with the Quill editor itself.

You define the toolbar container as such:

```
{
  toolbar: '#toolbar-container'
}
```

but then it wipes all buttons, as it believes it is a fully custom toolbar, so in your container you have to have all the buttons defined as such:

```
<div id="toolbar-container">
   <button class="ql-bold"></button>
  <button class="ql-italic"></button>
</div>
```

It seems it's impossible to define a container and buttons to be there, as the short hand is the same for both.

**Comment by SamRichards** [comment]
Thanks for the help.
