### ISSUE TITLE
angular ui bootstrap uib-tab in IE11 with nested forms all get active once I cut and paste in quill editor

### ISSUE THREAD

**Issue by ahmedsafwat** [KillerCodeMonkey/ng-quill#125]
I am using quill editor with ng-quill directive and I use angular ui bootstrap tabs. I face a problem only in IE11 when I am cutting and paste within the editor. Once I cut some text within editor and I try to move them in a different location in the editor. All the tabs they get active and all their content will displayed in one page. so I will see the tabs at the top and all the contents will be displayed one after another and the tabs will be no longer hide or show any content. This is happening only when I have nested forms.

When I have only one form it works fine. once I have two nested forms I get the above issue.

I already created a Codepen: https://codepen.io/ahmedsafwat/pen/eEdpZP

I use Angular 1.5.8 , Angular UI Bootstrap 0.14.3, Quill 1.1.5, ngQuill 2.0.2

**Comment by KillerCodeMonkey** [comment]
could you post a screen shot or a little video? i do not have the ability to test this IE11. But it sounds like you get a javascript error. 

Please use the latest releases of ng-quill and quill.

If this not resolves your issue try it without the forms or your custom code around.

Because on the demo.html in this repo i have multiple editors on one page, too
http://killercodemonkey.github.io/ng-quill/demo.html

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
did you solved the problem?

**Comment by ahmedsafwat** [comment]
Sorry Bengt I have been very busy lately. I apologies for not responding back that quick. Actually I did upgrade and had the same issue. I got it working by just getting rid of the nested form and having one form.

I tried to also attach for you a screenshot if that might help. As you can see in the following screenshot:

Before cutting and pasting any content:
![image](https://user-images.githubusercontent.com/4580881/29632411-ed5f9a3c-8810-11e7-95b3-1da6d192cef0.png)

After cutting and pasting part of the line in the body:
![image](https://user-images.githubusercontent.com/4580881/29632374-d3749762-8810-11e7-9dd2-93b589e10417.png)

Thanks!

**Comment by KillerCodeMonkey** [comment]
maybe you can simply post the links to these two codepens?

**Comment by ahmedsafwat** [comment]
It's already there in the first post. But anyway here is the link again: https://codepen.io/ahmedsafwat/pen/eEdpZP

**Comment by KillerCodeMonkey** [comment]
did you solved it on your own? I will not be able to look into it this soon, because . i have to set up an old windows machine and so on.
