### ISSUE TITLE
Formats array can be incongruent with what is defined in custom toolbar

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ng-quill#126]
This may or may not be a bug depending on how you look at it, but it could be worth documenting?

I have a button defined in the custom toolbar for adding images by URL so that an image tag with a source attribute gets injected into the text editor. I ran into a funny situation where pasted images were allowed in Firefox but no other browser, and get injected as base64 data. This can cause serious performance issues in something like a news feed with a lot of images.

The solution was to define a `formats` array which matched all of the buttons I included in my custom toolbar, because otherwise the default configuration passes in the `'images'` format.

**Comment by jziggas** [comment]
Actually it is a little more complicated it seems. By removing the `'images'` format I can't embed any images at all now. So I'm not sure how to allow image embeds but disallow pasting base64. Any ideas?

**Comment by tpartee** [comment]
You need to create your own plug-in for embedding images by URL/link
instead of as base64 - Quill's default embedding is via the base64 method
and anything else requires you to write your own code. Welcome to Quill!

**Comment by jziggas** [comment]
Images that are copied into the clipboard from your local machine get converted to base64 data, but images copied into the clipboard from the browser get their URLs passed in. This was a simple enough solution to filter out base64 data from incoming pastes:

```
editor.clipboard.addMatcher('img', (node, delta) => {
    let noop = {ops: {}};
    if (!delta) {
        return noop;
    }
    let url = delta.ops[0].insert.image;
    if (includes(url, 'data:image/')) {
        return {ops: {}};
    } else if (includes(url, 'http')) {
        let selection = editor.getSelection() || {index: 0};
        editor.insertEmbed(selection.index, 'image', url);
    }
});
```

With regard to the original title of this issue, it might still be worth making note that the editor will still allow all default formats if you create a custom toolbar. So for instance if you have a custom toolbar with only an italic button, all other formats can still be pasted in unless you explicitly set the formats array. A small distinction, just something I never realized before.

**Comment by KillerCodeMonkey** [comment]
my intention was to combine both: so that what you have configured through the service is something like a whitelist for all or you need to whitelist these things per editor.
