### ISSUE TITLE
on-editor-created callback in directive

### ISSUE THREAD

**Issue by Anubarak** [KillerCodeMonkey/ng-quill#127]
Hello,

first thank you very much for your work, it is great to have this editor in angular. I'm new to angular so my entire problem could be a terrible mistake in understanding the framework. So maybe my thoughts are all wrong and there could be a much smoother way to handle it - please keep that in mind.

Okey so: I created some kind of formbuilder in angular. That means I have an array of field types and I include different templates depending on the field type in my controller to build each field. One field type should be a quill editor.

The databinding works perfectly but I can't figure out how to access the 'on-editor-created' in my directive

This is my html
```
<div class="form-group">
    <ng-quill-editor
            theme="snow"
            ng-model="datasource"
            ng-blur=""
            on-editor-created="editorCreated(editor)"
    >
    </ng-quill-editor>
</div>
```

This is my directive
```
myApp.directive('thinDirective', function($compile,$templateRequest, configService) {
    return {
        restrict: 'A',
        scope: {
            datasource: "=",
            attributes:"=",
            index: "="
        },
        compile: function (element, attrs) {
            return function (scope, element, attrs) {
                $templateRequest(configService.angularTemplatePath + 'admin/forms/matrix/' + attrs.thinDirective + ".twig").then(function (html) {
                    element.append($compile(html)(scope));
                });
            }
        },
        link: function($scope){
            /**
             * callback after editor is created
             * @param editor
             * @param key
             */
            $scope.editorCreated = function (editor) {
                alert("test");
            };
        }
    }
});
```

Could you eventually explain me how to access the `on-editor-created` in my directive or in my parent scope?
Thanks for your time and sry for the trouble - like I said I started to use angular few days ago

**Comment by KillerCodeMonkey** [comment]
An example without a directive can be found here:
https://github.com/KillerCodeMonkey/ng-quill/blob/develop/demo.html

in your case a directive is the wrong approach to handle a custom template:

directives - Change the behavior (like even listeners) or the appearance of an existing dom node 
component - A directive with an own template :)

So you should go with the component.
https://toddmotto.com/exploring-the-angular-1-5-component-method/

I think the link step in a directive is to late, so you miss the editor on create event.

**Comment by Anubarak** [comment]
Thank you very much, that helps me to understand angular better and sorry for the trouble since it was not really related to your plugin and more to angular itself
