### ISSUE TITLE
Styling not being applied to the editor

### ISSUE THREAD

**Issue by mattjegan** [KillerCodeMonkey/ng-quill#133]
Hey, thanks for working on this project. I've recently been trying to integrate ng-quill into one of my projects and have managed to get the element to render on the screen with `<ng-quill-editor ng-model="$ctrl.title" on-editor-created="$ctrl.editorCreated(editor)" on-content-changed="$ctrl.contentChanged(editor, html, text)"></ng-quill-editor>` after following the instructions in the README however, the styling is completely wrong and I haven't found a way to fix it yet. Here is a preview of what I'm seeing:

![screen shot 2017-11-15 at 3 35 12 pm](https://user-images.githubusercontent.com/2116020/32819601-3a60b9d4-ca1e-11e7-96c1-53cde56e8611.png)

I've added `[ng-quill-editor] { display: block; }` to my css as per your suggestion and have also added the quill core css `@import "~quill/dist/quill.core.css";`.

If it matters, I'm using webpack and have added a rule to use `html-loader` for things in quill:
```
{
    test: /\.svg$/,
    include: [
        path.resolve(__dirname, 'node_modules', 'quill')
    ],
    use: [{
        loader: 'html-loader',
        options: {
            minimize: true
        }
    }]
}
```

Please let me know if there's any more information that I'm missing 😄

**Comment by KillerCodeMonkey** [comment]
You have to add the snow theme CSS AS well.

Am 15.11.2017 06:16 schrieb "Matthew Egan" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
does it work?

**Comment by mattjegan** [comment]
Sorry for the late response, timezones are a pain. Just tried it out and it did indeed work, I was missing the `theme="snow"` and also missing the import `@import '~quill/dist/quill.snow.css';` in my css. Thanks a lot for your help 😄

**Comment by deshario** [comment]
@mattjegan where to import that snow.css file and set theme="snow" ... can u provide little bit more info Thankx
