### ISSUE TITLE
How to manage more instances callback in same controller?

### ISSUE THREAD

**Issue by lucaarcangeli** [KillerCodeMonkey/ng-quill#134]
Hi there,
I've two distinct <ng-quill-editor> (readolny, used only to display text previously inserted) into the same page:
```
<ng-quill-editor id="detail-info-pane-description" class="detail-info-pane-description" 
        ng-model="mtng.description"
	on-editor-created="descEditorCreated(editor)"
	read-only="true">
</ng-quill-editor>

[...]

<ng-quill-editor id="detail-info-pane-note" class="detail-info-pane-note"
        ng-model="mtng.note"
	on-editor-created="noteEditorCreated(editor)"
	read-only="true">
</ng-quill-editor>
```
and in Controller:
```
$scope.descEditorCreated= function(editor) {
    // code here...
};

[...]

$scope.noteEditorCreated = function(editor) {
    // code here...
};
```
Unfortunatelly only the first callback is invoked and page is not rendered as expected. If I remove one of the two callback, all works like a charm. 
Could you please give me some hints?

Thanks in advance,

Luca.

**Comment by lucaarcangeli** [comment]
UPDATE: I'm sorry: after a fresh and mint check, I just realize that all the problems are casused by a fragment of JS code inside one of the callback that randomically (based on remote loaded data) generate an error. 
I'going to close the issue.

I apologize :)

**Comment by KillerCodeMonkey** [comment]
No probs ;). Glad you solved it :)
