### ISSUE TITLE
Fire on-content-changed only after second action

### ISSUE THREAD

**Issue by DenniLa2** [KillerCodeMonkey/ng-quill#135]
html:
`
    <ng-quill-editor ng-model="el.name"
                     on-content-changed="quill.onChange(editor, html, text, delta, oldDelta, source)">
`
js:
`
$scope.quill = {
      onChange: function (editor, html, text, delta, oldDelta, source) {
        console.log(' ---> ON QUILL');
}
`
Hi there!
Method $scope.quill.onChange fire only after second action. If i press only one symbol on keyboard - i don`t see in console ' ---> ON QUILL'

**Comment by KillerCodeMonkey** [comment]
strange can not reproduce this issue.

even in my demo page:
http://killercodemonkey.github.io/ng-quill/demo.html

check first editor

**Comment by DenniLa2** [comment]
I found cause. When initial value === undefined - quill not fire on first action. Thank You!

**Comment by KillerCodeMonkey** [comment]
so this is solved for you? then i will close the issue :)
