### ISSUE TITLE
Custom dropdown inside toolbar

### ISSUE THREAD

**Issue by frabnt** [KillerCodeMonkey/ng-quill#141]
What's the suggested way to add a custom dropdown in the toolbar? I tried something like:

```
<ng-quill-editor
    ng-model="title">
    <ng-quill-toolbar>
        <div>
            <span class="ql-formats">
                <select class="ql-custom" 
                          ng-model="myModel"
                          ng-change="select()">
                    <option value="first-value"></option>
                    <option value="second-value"></option>
                    <option value="third-value"></option>
                </select>
            </span>
        </div>
    </ng-quill-toolbar>
</ng-quill-editor>
```

With the above solution I have two problems:

1.  I'd like to avoid the `quill:toolbar ignoring attaching to disabled format custom` warning.
2.  The first option is always the one selected by default even if I'm not using the `selected` attribute in the template. I would like to have no option selected by default and do "some operations" when an option is clicked.

**Comment by KillerCodeMonkey** [comment]
Hey there, you should ask that in the quilljs repo. I think i cannot help
you with this questions.

Am 24.01.2018 10:55 vorm. schrieb "Francesco Benedetto" <
notifications@github.com>:

**Comment by frabnt** [comment]
Closing issue.
