### ISSUE TITLE
Drag and Drop text into the editor

### ISSUE THREAD

**Issue by MustafaASK** [KillerCodeMonkey/ng-quill#142]
I would like to drag and drop (predetermined) text at the cursor location (not at the beginning) in the editor. This will be useful in creating templates using the editor. Is it possible?

I did not see something like this in quill any other text editor other than https://github.com/froala/angular-froala, which is subscription based. Would love to have it in quill.

**Comment by KillerCodeMonkey** [comment]
I only provide this repo AS an easy to use angularjs wrapper. If you want a
drag and drop ability, you could add this as a custom quill addon/module or
ask at the original quill repository.

If quilljs will support drag and drop functionality i would provide it also
to ng-quill.

But i will not add additional functionality that should be impemented in
quilljs first

Am 05.02.2018 18:26 schrieb "MustafaASK" <notifications@github.com>:
