### ISSUE TITLE
How to add custom menu to toolbar

### ISSUE THREAD

**Issue by DenniLa2** [KillerCodeMonkey/ng-quill#144]
Hello!
My code look like this:
        
    <span class="ql-formats">
        <select class="ql-custom">
            <option class="ql-first-value" value="first-value" title="first"></option>
        </select>
    </span>
    

In console I see quill:toolbar ignoring attaching to nonexistent format custom ...
I dont understand, where I should place event handlers and how add custom menu. Help me please! Some code, pls!

**Comment by KillerCodeMonkey** [comment]
Did you checked quilljs documentation or asked at the quill repository?
This is only an angular wrapper.

But i would guess quill checks for existing modules registered if you use
css classes starting with "ql-". That is why formats are added with
ql-format and so on ;)

Am 21.02.2018 22:04 schrieb "Denni" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
any updates @DenniLa2 if it comes too difficult - please ask in the quilljs repo, thanks
