### ISSUE TITLE
How can I set "bounds" to be the current element

### ISSUE THREAD

**Issue by free-easy** [KillerCodeMonkey/ng-quill#145]
In order to fix [this issue](https://github.com/quilljs/quill/issues/1103) I need to set "bounds" to the current element.

**Comment by KillerCodeMonkey** [comment]
it is not possible for now. to set this initially, because the element is created on the fly.

you can simply try to wrap the quill-editor in another div (without special stylings) and set the bounds to that element.

**Comment by KillerCodeMonkey** [comment]
is this working for you?

**Comment by free-easy** [comment]
Sorry I haven't tried yet.
This evening I should have time to test it.

I'll let you know.

**Comment by free-easy** [comment]
I've tried but it doesn't work

**Comment by free-easy** [comment]
```
var app = angular.module("myModule")
	.directive("richEdit", RichEditDirective);

function RichEditDirective() {
	return {
		restrict: "E",
		templateUrl: "views/RichEdit.html",
		compile: compile,
		scope: true,
	};

	function compile($element) {
		// pass all attributes to the inner ng-quill-editor we're encapsulating

		// get the actual dom element from the jqLite object $element
		var domElement = $element[0];

		var editor = $element.find("ng-quill-editor");

		// copy all the attributes to ng-quill-editor
		angular.forEach(domElement.attributes, function(attribute) {
			editor.attr(attribute.name, attribute.value);
		});

		editor.attr("bounds", "$element");

		// remove all the attributes on current element
		while(domElement.attributes.length > 0) {
			domElement.removeAttribute(domElement.attributes[0].name);
		}

		return function($scope, $element) {
			$scope.$element = editor[0];
		};
	}
}
```

**Comment by KillerCodeMonkey** [comment]
try the latest release 3.6.0 and pass `bounds="self"` to the editor tag

**Comment by free-easy** [comment]
Thank you very much. I've tried and it works!
I only want to point out that it should be `bounds="'self'"`, since its a binding of type "<" and not "@".

**Comment by KillerCodeMonkey** [comment]
jarp, you are right :)

**Comment by mattshma** [comment]
I'm already set bounds as follows:
```
QuillModule.forRoot({
      modules: {
        syntax: true,
      }
      bounds: 'self',
    }),
```
but when click link button, It's still cut off by the edge.

![image](https://user-images.githubusercontent.com/3884630/72503925-cc6a3e80-3877-11ea-8e18-7cd81c373941.png)

My ngx-quill version is 7.3.12 and quill version is 1.3.6, is somewhere I set wrong? thanks.
