### ISSUE TITLE
quill.module.ts:13 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by joscampbell** [KillerCodeMonkey/ng-quill#146]
Trying to get this to work with angular 4, and ngx-quill. Trying to get a working rich editor that works in IE (placeholder, etc.).
Note: I have js and css files imported. 

Error:
quill.module.ts:13 Uncaught ReferenceError: require is not defined
    at Object.__decorate (quill.module.ts:13)
    at __webpack_require__ (quill.module.ts:13)
    at Object.<anonymous> (quill.module.ts:13)
    at __webpack_require__ (quill.module.ts:13)
    at Object.__decorate (quill.module.ts:13)
    at __webpack_require__ (quill.module.ts:13)
    at quill.module.ts:13
    at quill.module.ts:13
    at webpackUniversalModuleDefinition (quill.module.ts:13)
    at quill.module.ts:13

**Comment by KillerCodeMonkey** [comment]
I think you shoul open this issue on ngx-quill ;). Ng-quill is for
angularjs 1.x.

If you want to use angular 4, the last ngx-quill Version is 1.6.0. after
that i only support angular 5.

So you should install ngx-quill and simply import the QuillModule from
'ngx-quill'. I tested it with webpack and ng-cli.

Check out the readme And my demo repo, how the build process could look
like.

**Comment by KillerCodeMonkey** [comment]
a hint for you - you need some changes if you want to use quilljs and ngx-quill with serverside rendering

checkout existing issues:
https://github.com/KillerCodeMonkey/ngx-quill/issues/91
https://github.com/KillerCodeMonkey/ngx-quill/issues/71
https://github.com/KillerCodeMonkey/ngx-quill/issues/57

**Comment by ThePatzen** [comment]
@joscampbell: Did you get rid of this error message? 

In my case the Editor work's fine but i still see this "require" error message in the browser console...

**Comment by tokaika** [comment]
@ThePatzen     hello。。。me  too。。i  also have the same problem 。。。did  you solved it？  require problem。。

**Comment by fergalmoran** [comment]
I'm also getting this error but only in production build and it's preventing my site from loading.
I'm not using server side rendering.

**Comment by joscampbell** [comment]
i did not.. just been dealing with it.. in console, as app still works for now.

**Comment by tokaika** [comment]
hah  me  too 。。。

**Comment by ThePatzen** [comment]
@tokaika: I did fix this using the following fix: https://github.com/KillerCodeMonkey/ngx-quill/issues/91

**Comment by tokaika** [comment]
@ThePatzen  thanks you for  notice me。。i also  resolved it 。。。😊

**Comment by KillerCodeMonkey** [comment]
nice! glad you got it!
