### ISSUE TITLE
app.component('ngQuillEditor',.....Not a function

### ISSUE THREAD

**Issue by JappanBhavsar003** [KillerCodeMonkey/ng-quill#148]
I am facing this error in ionic V1 and ionicMaterial tenmplate (use)

Error : 
```
ng-quill.js:76 Uncaught TypeError: app.component is not a function
    at ng-quill.js:76
    at ng-quill.js:8
    at ng-quill.js:10
```

**Comment by KillerCodeMonkey** [comment]
which angular version are you using?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
closed due to inactivity

**Comment by bjitpatra1305** [comment]
@KillerCodeMonkey I am also facing the same issue any idea how to solve it. My company codebase is using  AngularJS v1.4.3 . Is it possible to use this package without changing the angularjs version?

**Comment by KillerCodeMonkey** [comment]
v 1.4.4 should use angular 1.4 but i will not garantuee or fix any issues in that old versions ;)
