### ISSUE TITLE
How to Play the Recorded video in quill editor

### ISSUE THREAD

**Issue by vibingopal** [KillerCodeMonkey/ng-quill#150]
Hi Team,

I am trying to append the contents of recorded video into Quill Editor. At this moment once the recording is stopped, iam able to see the  blob object getting appended to the editor but it is not playable.  Could you please help

when i open the same url in different tab, it is getting played. 

![image](https://user-images.githubusercontent.com/17860925/38363016-96f204d0-3898-11e8-81d1-42d9bc56fbe0.png)

**Comment by vibingopal** [comment]
I tried to append the video control into the editor after stopping. But noting is getting displayed in the quil editor.

 this.editorContent = this.video;

![image](https://user-images.githubusercontent.com/17860925/38364670-345b7610-389f-11e8-896b-26856910ecfb.png)

**Comment by KillerCodeMonkey** [comment]
dude, i am the same guy providing ngx-quill :)
There is no team... simply me ^^

simply check how the video format works: if you add a video this html-code is added:
```<iframe class="ql-video" allowfullscreen="true" src="https://www.youtube.com/embed/2JkfBTQokTY?showinfo=0" frameborder="0"></iframe>```
 
Maybe that helps or not. you need an format that creates a video tag for you that quill can support it.

greets.

Such question should be asked on stackoverflow ;). And maybe you will get faster and better responses there.

**Comment by vibingopal** [comment]
Hi.. I am sorry for mentioning as team _/\_ .

I tried to insert the blob object(blob:http://localhost:4200/0f96ae12-431f-4cdc-945b-07ad8c6) in the embeded url, but the video is not getting played.
and i frame is showing the src as blank.
<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="about:blank"></iframe>

So , do i need to convert the video before appending the object.

**Comment by lakinmohapatra** [comment]
I am assigning following html to form control value of quill editor.
<div><img class="img-quill" src="http://localhost:8080/media/ea456b4bffe363a7.png"></div><div><br></div><video controls="controls" class="ql-video" width="100%" height="100%" player-source="http://localhost:8080/media/7dd839e1f7989dbb.mp4"><source src="http://localhost:8080/media/7dd839e1f7989dbb.mp4" type="video/mp4"></video><div><br></div>

image is showing. But video is not showinng. What might be the cause. Please help.
