### ISSUE TITLE
ng-quill or quill memory leak in Firefox in AngularJS 1.6 and uiRouter

### ISSUE THREAD

**Issue by cschwaderer** [KillerCodeMonkey/ng-quill#157]
I'm not sure whether the issue below is related to quill or ng-quill. I have, however, posted it on the quill repository (https://github.com/quilljs/quill/issues/2088) almost two weeks ago - without any reaction. So, maybe it is indeed related to the AngularJS wrapper. Anyway, here goes again.

It seems that a quill editor in a ui-Router state template of an Angular 1.6 app prevents the whole state/scope from being garbage collectible in Firefox.

**Steps for Reproduction**

1. **Either** go with Firefox to JSfiddle https://jsfiddle.net/ur24r1Lk/
**or** deploy the code below on a local web server and open it in Firefox:

```
<!DOCTYPE html>
<html ng-app="myNgQuillTestApp">

  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.snow.css">
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.bubble.css">
    <script data-require="angularjs@1.6.10" data-semver="1.6.10" src="https://code.angularjs.org/1.6.10/angular.min.js"></script>
    <script src="//unpkg.com/@uirouter/angularjs@1.0.7/release/angular-ui-router.min.js"></script>
    
    <script type="text/javascript" src="//cdn.quilljs.com/1.3.6/quill.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ng-quill/3.7.1/ng-quill.min.js"></script>
        
    <script>
    var app = angular.module('myNgQuillTestApp', ['ui.router','ngQuill']);
      
      /* UI router state definitions */
      app.config(function($stateProvider) {
      var small_stateState = {
          name: 'small_state',
          url: '/small_state',
          template: '<h3>Nothing here</h3>'
      }

      var quill_stateState = {
          name: 'quill_state',
          url: '/quill_state',
          controller: 'stateWithQuillCtr',
          template: '<h3>State with quill</h3><ng-quill-editor ng-model="fooHooHoo"></ng-quill-editor><div ng-repeat="outer in iAmVeryBig"><div ng-repeat="inner in outer">{{inner}}</div></div>'
      }
      $stateProvider.state(small_stateState);
      $stateProvider.state(quill_stateState);
      /* End of: UI router state definitions */
      
    });

    app.controller('stateWithQuillCtr', ['$scope',function ($scope) {
    
      /* Big array to make memory differences much more significant */
      $scope.iAmVeryBig = [];
      for(var i = 0; i < 200; i++) {
       var newArr = [];
       for(var j = 0; j < 200; j++) {
          newArr.push("Inner: " + i + " -- " + j);
        }  
       $scope.iAmVeryBig.push(newArr);
      }
      
    }]);
    
    </script>
  </head>

  <body>
    <a ui-sref="small_state" ui-sref-active="active">Small state</a>
    <a ui-sref="quill_state" ui-sref-active="active">State <b>with quill</b></a>

    <ui-view></ui-view>
  </body>
</html>
```

(I personally prefer the latter option for memory investigation because that way I can be sure it's not the fiddle/plunker itself causing the problem.)
2. Trigger a manual garbage collection (visit about:memory and click "Free memory" -> "GC")
3. Take a Heap snapshot (F12 -> Memory -> Take snapshot) 
4. On the example webpage provided, click "State with quill" and wait till loaded (the template is on purposed bloated with a big array to make the memory difference more significant).
5. Click on "Small state"
6. Trigger again a garbage collection
7. Take again a heap snapshot

**Expected behavior**:
The amount of memory used in "small state" should be more or less the same after having visited and closed the state with the quill editor.

**Actual behavior**:
After having visited the state with the quill editor, the amount of memory used is much bigger. The existence of quill obviously prevents the memory from being collected. Kicking the quill editor out of the template, solves the problem: The memory gets collected.

**Platforms**:
Firefox version 58.0.1
Ubuntu 16.10

**Version**:
Quill version 1.3.6, ng-quill 3.5.1"

**Firefox dominators view screenshot**
![image](https://user-images.githubusercontent.com/18464127/39290886-65f8f8bc-4931-11e8-84a3-1d34665a1b64.png)
Also this screenshot point into the direction that the problem is quill-related.

**Weird additional infos on Chrome**
Chrome definitely has also a quill-related memory problem in my (real-world) application. But it seems, Chrome is under some strange circumstances able to cope with it. 
For Chrome, I was not able to isolate the problem into a small demo/plunker. In Chrome it was - strange enough - dependent not only on quill, but the HTML name-attribute of four vanilla inputs, the user-defined language of my web application (switching to English solved the problem, whereas in German, it was always there) and - to make the confusion even bigger - in Chrome the problem was just there in Ubuntu, while in Windows 7 everything was fine concerning the memory.

**Comment by KillerCodeMonkey** [comment]
Maybe it is more or less related how You are using quilljs angular and so
on. I Do Not Know the latest ui Router, but. Maybe There are some Caching
mechanis to reuse components.

You should keep in mind that quilljs is Part of the Window Object. I Do Not
Know, If there is an opportunity to access quill instances through that. So
check If Your quill instance is not longer existing and it should be fine.

And some hint. Since angular 1.5 You should Use components and component
Routing. There You have the component life cycle to handle such things very
elegant, like doing cleanup work.

But i used this with ionic and never got memory issues.



cschwaderer <notifications@github.com> schrieb am Di., 8. Mai 2018, 13:43:

**Comment by cschwaderer** [comment]
Thanks for your reply!

1. Refactoring my app for AngularJS 1.5 components won't happen. The code base is simply too huge. 
2. I don't think that the problem is directly routed in uiRouter, because without (ng-)quill, the memory is correctly cleared both in Firefox and in Chrome. uiRouter doesn't seem to have a general memory problem.
3. Of course, the quill instance lives on as you can see from the screenshot. That is exactly the problem. The question is: Why does it live on? And how to solve that? Killing all quill instances in the window object with `$rootScope.$on("$stateChangeStart"`?

**Comment by KillerCodeMonkey** [comment]
yep i see the only possibility to remove them with a routing event then. So stateChangeStart or success. which quilljs version and ng-quill do you use?


Because since quilljs 1.0 they should not store global instances for garbage collection

**Comment by cschwaderer** [comment]
I'm using quill version 1.3.6, ng-quill 3.5.1

**Comment by KillerCodeMonkey** [comment]
May it possible that you test this without ng-quill?

simply use quilljs and init an editor by your self https://quilljs.com/docs/quickstart/#quickstart and check if the problem still exists?

**Comment by cschwaderer** [comment]
It seems indeed that the problem is gone with just plain quill. This is the code I ended up with, putting the quill definition in the controller:


```
<!DOCTYPE html>
<html ng-app="myNgQuillTestApp">

  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.snow.css">
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.bubble.css">
    <script data-require="angularjs@1.6.10" data-semver="1.6.10" src="https://code.angularjs.org/1.6.10/angular.min.js"></script>
    <script src="//unpkg.com/@uirouter/angularjs@1.0.7/release/angular-ui-router.min.js"></script>
    <script type="text/javascript" src="//cdn.quilljs.com/1.3.6/quill.js"></script>
    <script type="text/javascript">
    var app = angular.module('myNgQuillTestApp', ['ui.router']);
      
      /* UI router state definitions */
      app.config(function($stateProvider) {
      var small_stateState = {
          name: 'small_state',
          url: '/small_state',
          template: '<h3>Nothing here</h3>'
      }
      
      var quill_stateState = {
          name: 'quill_state',
          url: '/quill_state',
          controller: 'stateWithQuillCtr',
          template: '<h3>State with quill</h3><div id="editor"><p>Hello World!</p><p>Some initial <strong>bold</strong> text</p><p><br></p></div><div ng-repeat="outer in iAmVeryBig"><div ng-repeat="inner in outer">{{inner}}</div></div>'
      }
      $stateProvider.state(small_stateState);
      $stateProvider.state(quill_stateState);
      /* End of: UI router state definitions */
      
    });

    app.controller('stateWithQuillCtr', ['$scope',function ($scope) {
        
      var quill = new Quill('#editor', {  theme: 'snow'  }); 
    
      /* Big array to make memory differences much more significant */
      $scope.iAmVeryBig = [];
      for(var i = 0; i < 200; i++) {
       var newArr = [];
       for(var j = 0; j < 200; j++) {
          newArr.push("Inner: " + i + " -- " + j);
        }  
       $scope.iAmVeryBig.push(newArr);
      }
      
    }]);
    </script>
  </head>

  <body>
    <a ui-sref="small_state" ui-sref-active="active">Small state</a>
    <a ui-sref="quill_state" ui-sref-active="active">State <b>with quill</b></a>

    <ui-view></ui-view>
  </body>
</html>
```

**Comment by KillerCodeMonkey** [comment]
strange thing, i did not hold any global references in my component 🤔

**Comment by KillerCodeMonkey** [comment]
@cschwaderer hey, seems like it has something todo, that you directly push the array items to the scope. so you are updating more than 200 times the scope. each scope change rerenders the view.

So i think you are rendering 200 quill editors than.
If build up your demo array and only set the final array on the scope, there is no memory leak.

**Comment by cschwaderer** [comment]
I cannot confirm that observation. Having changed the code to

```
var bigArrayPrepare = [];
      for(var i = 0; i < 200; i++) {
       var newArr = [];
       for(var j = 0; j < 200; j++) {
          newArr.push("Inner: " + i + " -- " + j);
        }  
       bigArrayPrepare.push(newArr);
      }
      
      $scope.iAmVeryBig = bigArrayPrepare;
```


I still get the same behaviour.

Anyway: Pure DOM-rendering of (ng-)quill shouldn't be a problem and shouldn't cause any memory leaks. And changing the scope 200 times while being in one state, is something which actually could happen in a real-world application.

**Comment by KillerCodeMonkey** [comment]
yeah but i can not reproduce the error now with your fiddle... i reloaded the page and my memory snapshots are all 13mb-16mb ... even if i am on the quill page or not

**Comment by cschwaderer** [comment]
That's strange. I can observe that memory leak in Firefox on three machines with both version 58 and 59 and both on Kubuntu 16.04 and on Windows 7.
Don't know what to do about it. If you cannot reproduce it, you can't fix the problem, obviously.

So, could you maybe tell me, what's the exact path of the quill instanc(es) in the window object to be set to null?

**Comment by KillerCodeMonkey** [comment]
thats the curious part... there are no global quill instances --> check the migration guide of quilljs to 1.0.0.

they removed the `remove` function because no global instances are stored Oo

**Comment by KillerCodeMonkey** [comment]
do not know how to solve this, because i need to bind it to this, to add the angular functionalities.

Maybe you could investigate if there is the possibility to remove the listeners?
I will try something in the meantime

**Comment by KillerCodeMonkey** [comment]
could you test your code with https://github.com/KillerCodeMonkey/ng-quill/blob/develop/src/ng-quill.js ? i set the "editor" var to null $onDestroy.

It is only a shot in the dark

**Comment by cschwaderer** [comment]
Thanks! Well, I had only tried that, was also my first thought. However, it's too primitive, probably. It doesn't change anything. I guess, the problem is somewhat deeper.

**Comment by cschwaderer** [comment]
I'm still on this and was able to further narrow down the problem.
It seems that any reference to $scope, the controller or whatever inside a quill-editor event handler prevents the $scope form being garbage-collected in Firefox.
Leaving aside everything which is obviously not related to the problem, my minimized ng-quill looks now like this:

```
(function ngQuillFunc01 (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['quill'], factory)
  } else if (typeof module !== 'undefined' && typeof exports === 'object') {
    module.exports = factory(require('quill'))
  } else {
    root.Requester = factory(root.Quill)
  }
}(this, function ngQuillFunc02(Quill) {
  'use strict'

  var app
  // declare ngQuill module
  app = angular.module('ngQuill', [])

  app.component('ngQuillEditor', {
    controller: ['$scope', '$element', '$timeout', function ngQuillFunc06($scope, $element, $timeout) {
            
      var editorElem
      var editor
      
      this.$postLink = function ngQuillFunc10() {
        // create quill instance after dom is rendered
        $timeout(function  ngQuillFunc11() {
          this._initEditor(editorElem)
        }.bind(this), 0)
      }

      this._initEditor = function  ngQuillFunc12(editorElem) {
        var $editorElem = angular.element('<div></div>')
        var container = $element.children()

        editorElem = $editorElem[0]

        container.append($editorElem)

        editor = new Quill(editorElem, {})

        editor.on('text-change', function () {
          if (1==2) {
             console.log($scope); // Any arbitrary reference to $scope. It doesn't matter that it never will get executed
          }
        })
      }
    }]
  })

  return app.name
}))
```
The crucial line is: `console.log($scope);` - without this line, there is no memory leak. As soon as `$scope` becomes part of the `editor.on('text-change', function () {` closure it seems that it is retained forever.
And at this point, I'm now not sure anymore whether ng-quill is actually the problem. The root of the problem could perhaps be the way quill handles event handlers. Unfortunately, the quill guys rarely respond on anything on github.

**Comment by KillerCodeMonkey** [comment]
did you have any updates on this?

**Comment by cschwaderer** [comment]
Not really big updates. I tried a lot of things - all in vain. However, fortunately, I was at least able to narrow down the issue even more. I sort of rewrote the problematic bit as an AngularJS directive just to rule out that the problem is the component structure.

The code looks now like this:

```
angular.module('ngQuill',[]);
angular.module('ngQuill').directive('ngQuillEditor',
    [function()
        {
           return {
                restrict: 'E',
                scope: {
                },
               controller: ['$scope','$element',function($scope,$element) {
                   var editor = new Quill($element[0], {});
                   editor.on('text-change', function () {
                   if (1==2) {
                        console.log($scope);
                    }
                   });
               }]
            };
        }]);
```

- and the memory leak is still there.

**Comment by cschwaderer** [comment]
I think I've knocked it off. It seems to necessary to unregister the event listeners like so:

```
var selectionChangeEvent = editor.on('selection-change',  ....
var textChangeEvent = editor.on('text-change', ...

$scope.$on('$destroy', function() {
		 textChangeEvent.removeListener('text-change');
		 selectionChangeEvent.removeListener('selection-change');
});
```
At least according to my tests, that solves the problem in Firefox. The weird Chrome behavior is still to be tested.

**Comment by KillerCodeMonkey** [comment]
added in 2.8.0
