### ISSUE TITLE
Tried to load angular more than once : posted on stackoverflow

### ISSUE THREAD

**Issue by harshu13** [KillerCodeMonkey/ng-quill#161]
Please look into the issue, may be I am wrong somewhere, but I am not able to resolve this issue:

[https://stackoverflow.com/questions/51349189/uncaught-error-jqlitenosel-http-errors-angularjs-org-1-5-11-jqlite-nosel](url)

**Comment by KillerCodeMonkey** [comment]
yeah but checkout the demo.html hier in the repo it is linked... there is no such error ;)

so sure you are loading angular twice in your project. ng-quill does not load angular. So check your code or buildprocess.

**Comment by KillerCodeMonkey** [comment]
and additional to the warning - the error jqlite nosel means you are using some tags or angular.element-selector which is not supported ;)

**Comment by KillerCodeMonkey** [comment]
Maybe you forgot to import some angular-modules or got some typos by the usage of the components?

**Comment by KillerCodeMonkey** [comment]
Yeah but create a codepen or something else to reproduce the error. Copy my
Demo.html and Test it... No error. So maybe You are loading angular a
secondtime on Your own, E.g. At the end of Your Body or somewhere else. And
the duplicate warning is not the mainproblem for You... The jqlite nosel
is...

Harshal Khatri <notifications@github.com> schrieb am Mo., 16. Juli 2018,
08:28:

**Comment by KillerCodeMonkey** [comment]
Simply add quill to your build-process?

I am not here, to get everyones build process fixed. So I only documented the simple way, to use it.
If you are using es6 modules you could simply `import ng-quill` instead of loading the it via a script tag. Just sayin…

But it is your project and you should know how you add new dependencies to it ;)

And without code of your build-process i am not able to help you.

**Comment by harshu13** [comment]
Thanks a lot, @KillerCodeMonkey!! for your prompt support, it's working now.

**Comment by KillerCodeMonkey** [comment]
Please close the issue and if helpful, post the solution ;)

**Comment by harshu13** [comment]
@KillerCodeMonkey: You have already closed this issue. 

I always add the dependency using bower install or npm install and everything will work automatically, and since this was the first library that needs to add script I was just curious why it didn't work automatically, and I was not sure if it can be part of build process or not (since all of the 3rd party dependencies I used I do not need to do anything manually).

But now without adding scripts it's working, previously it was not working for some reason. gulp is loading quill, ngQuill and angular dependency on its own. I was confused and thought its mandatory to add these in script tags after reading the document. Thanks for your help and library :)

**Comment by KillerCodeMonkey** [comment]
> @KillerCodeMonkey <https://github.com/KillerCodeMonkey>: You have already closed this issue.
> 
> 

Okay, forgot that :)
> I always add the dependency using bower install or npm install and everything will work automatically, and since this was the first library that needs to add script I was just curious why it didn't work automatically, and I was not sure if it can be part of build process or not (since all of the 3rd party dependencies I used I do not need to do anything manually).
> 
> But now without adding scripts it's working, previously it was not working for some reason. gulp is loading quill, ngQuill and angular dependency on its own. I was confused and thought its mandatory to add these in script tags after reading the document. Thanks for your help and library :)
> 
> 

Do not use bower, please :)
