### ISSUE TITLE
Problem opening image media files with IONIC (Android version)

### ISSUE THREAD

**Issue by Juanancon** [KillerCodeMonkey/ng-quill#162]
Hi! I'm using ng-quill with ionic and everything works fine (thanks KillerCodeMonkey!!) but i've an issue with Android ussage; in the toolbar if i try to select image media this brokes the app (just when try to open the gallery)... this doesn't happens on iOS version. I try to give Android Permissions but doesn't fix the problem

Anyone have a workaround for this?

Thanks in advance

**Comment by KillerCodeMonkey** [comment]
any updates?
