### ISSUE TITLE
How to assign default handlers to custom buttons?

### ISSUE THREAD

**Issue by ArsalanSavand** [KillerCodeMonkey/ng-quill#163]
So this is my custom module:
```js
$scope.options = {
  toolbar: [
    ['bold', 'italic', 'underline', 'strike'],
    ['link', 'image', 'blockquote', 'code-block', { 'list': 'bullet' }],
    [{ 'header': [1, 2, 3, false] }],
    [{ 'direction': 'rtl' }, { 'align': [] }],
    ['clean'],
    [{ 'customList': [{ 'color': [] }, { 'background': [] }, { 'list': 'ordered' }] }]
  ]
};
```

I want to attach default handlers to my custom dropdown.
For example, in 'customList' dropdown I want every child have their own default handlers.

**Comment by ArsalanSavand** [comment]
@KillerCodeMonkey Yes the best way for custom buttons are custom toolbar, but what if I want to add default handlers . I did search for this issue and I got no results.

**Comment by KillerCodeMonkey** [comment]
@ArsalanSavand i am not the right person for that. you should ask this in the quilljs repo, how to do it. i think if you know how it is done in plain quilljs, you can do it in the sameway with ngx-quill.

I am not that quilljs expert ;)
