### ISSUE TITLE
Pasting text into body doesn't trigger a change

### ISSUE THREAD

**Issue by chanpod** [KillerCodeMonkey/ng-quill#164]
In Chrome, if I copy paste text and that's it, the ng-model isn't updated with the new value. It's like the component is only changing on key press. But if I just hit the spacebar or whatever, it updates properly.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by chanpod** [comment]
My apologies on the delay. Work has been crazy busy. I was able to successfully reproduce on safari and firefox.

**Comment by chanpod** [comment]
I've updated the original comment with a more clear procedure to reproduce.

**Comment by KillerCodeMonkey** [comment]
should be fixed in 4.2.0
