### ISSUE TITLE
Color and Background Color information are not loaded in the variable

### ISSUE THREAD

**Issue by arkachego25** [KillerCodeMonkey/ng-quill#165]
Hello everyone,

Can you please suggest me a way to extract the color and background color information, being rendered inside the ng-quill-editor while binding it with a variable?

The snap is attached herewith. Please also find the pen [here](https://codepen.io/anon/pen/ajjBeZ?editors=1010).

![snap](https://user-images.githubusercontent.com/28679384/43686579-e40fa7c4-98e5-11e8-864a-6993325b3643.png)

Thanks in advance.

Arka.

**Comment by KillerCodeMonkey** [comment]
You can simply check the deltas of changes - there is an callback called `on-content-changed `https://github.com/KillerCodeMonkey/ng-quill#callbackoutputs

There you get on the fly the content object, html and text representation of the editor content and a delta object, containing such information.

In any other case you can use the `content` object - it is simply a json-object/array if operations, where you see which color is used.
