### ISSUE TITLE
Set height of the editor

### ISSUE THREAD

**Issue by ozairsajid** [KillerCodeMonkey/ng-quill#166]
@KillerCodeMonkey Can we please have a similar feature like what you added in ngx-quill? 
https://github.com/KillerCodeMonkey/ngx-quill/issues/58#issuecomment-324249465

**Comment by ozairsajid** [comment]
I used `on-editor-created()` and used the `editor` reference to set the height.

**Comment by KillerCodeMonkey** [comment]
Or Use simple css but with the ::ng-deep Pseudo selector to avoid the
viewencapsulation.

ozairsajid <notifications@github.com> schrieb am Mo., 13. Aug. 2018, 20:04:

**Comment by efstathiosntonas** [comment]
@ozairsajid  can you please provide an example? Thanks

**Comment by ozairsajid** [comment]
One template file having multiple instances of ng-quill. We had to dynamically set different height for each of the instance.

**Comment by efstathiosntonas** [comment]
thanks for the reply, can you share the code that sets the height? I have only one editor.

**Comment by ozairsajid** [comment]
Template:
```<ng-quill-editor ng-model="panel.value"
                             width="100%"
                             on-editor-created="quillHeight(editor)"
                <ng-quill-toolbar></ng-quill-toolbar>
            </ng-quill-editor>
```

JS
```
$scope.quillHeight = function (editor) {
                                    editor.container.style.height = '500px';
                    };
```

**Comment by deshario** [comment]
@ozairsajid 
Setting height is working but i'm trying to set placeholder on-editor-created as yours but it's not working 
`editor.options.placeholder = 'newplaceholder';`
<img width="879" alt="Screen Shot 2563-03-04 at 11 11 57" src="https://user-images.githubusercontent.com/11426727/75844565-fcaa7400-5e08-11ea-8678-ba758d5c8b91.png">

**Comment by deshario** [comment]
<img width="774" alt="Screen Shot 2563-03-04 at 11 33 40" src="https://user-images.githubusercontent.com/11426727/75845560-100b0e80-5e0c-11ea-991f-4a23e9bda60a.png">


> Placeholder is'nt updating

**Comment by ozairsajid** [comment]
We are setting the placeholder as an attribute in the template and not through the editor option.

`<ng-quill-editor ng-model="modelObject"
                             read-only="::property.isReadOnly || checkReadOnly(property,panel)"
                             ng-required="{{::property.isRequired}}"
                             theme="{{panel.skin || moduleInfo.skin}}"
                             width="100%"
                             placeholder="{{::property.description}}"
                             on-editor-created="quillHeight(editor, property, panel)">
                <ng-quill-toolbar></ng-quill-toolbar>
</ng-quill-editor>`

**Comment by KillerCodeMonkey** [comment]
@deshario aaaand this ticket is not even about the placeholder... and everything else is answered in another issue you created... if you want an answer just search for an existing and correct ticket or create A SINGLE new one.

@ozairsajid but thanks for sharing your answer!

**Comment by deshario** [comment]
@KillerCodeMonkey  OK Thankx
