### ISSUE TITLE
Using Only Inline Css with Angular 5

### ISSUE THREAD

**Issue by upexcel** [KillerCodeMonkey/ng-quill#167]
Hi. Thanks for your efforts for making this wonderful editor.
but can you please tell me how to use inline styles instead of classes. in the editor.
i have to create Email templates and i can't use classes for that.

**Comment by KillerCodeMonkey** [comment]
You should Use ngx-quill for angular 5 and Not ng-quill

upexcel <notifications@github.com> schrieb am Do., 27. Sep. 2018, 15:50:
