### ISSUE TITLE
Font color is not applying to the pasted phrases.

### ISSUE THREAD

**Issue by sudarshanadayananda** [KillerCodeMonkey/ng-quill#168]
Hi KillerCodeMonkey,

I am using your amazing editor in one of my AngularJS project.
When I copy a paragraph from external web site and paste it to the ngQuill text editor font color is not applying.
Any help is appreciated.
Thanks.

**Comment by KillerCodeMonkey** [comment]
because the editor does not know what color the text is ;). Quill formats the color with classes.

checkout quilljs.com or the quilljs repo ;)

**Comment by sudarshanadayananda** [comment]
Thanks
