### ISSUE TITLE
FullScreen support in Editor

### ISSUE THREAD

**Issue by KinjalAkhani** [KillerCodeMonkey/ng-quill#169]
Thanks for this quill editor. It is very helpful Rich Text Editor.

For my project i need full screen tool, not able to see it in this editor so could anybody advise me for same.

**Comment by KillerCodeMonkey** [comment]
Dude read carfully. Quilljs IS the Editor. Ng-quill and ngx-quill are both
wrappers.

For angular 1 and >2.



Am Di., 13. Nov. 2018, 12:29 hat KinjalAkhani <notifications@github.com>
geschrieben:
