### ISSUE TITLE
How get blot contents to save to database?

### ISSUE THREAD

**Issue by ChuckIrvine** [KillerCodeMonkey/ng-quill#171]
When the user clicks a "Save" button, I want to get the blot contents of the editor instance so that I can save it to a database via a rest call. How can I get the blot contents? While I'm at it.... When I later pull a blot from my database, how do I initialize an editor with the retrieved blot?

Thanks

**Comment by KillerCodeMonkey** [comment]
Check the readme you can Set the Format you want to get and Set through a
formControl or ngmodel

Set it to json to Pass and get json String of the Blot content or use
Object to directly Work with the quilljs content Objects.

Cheers

Am Mo., 21. Jan. 2019, 17:09 hat Chuck <notifications@github.com>
geschrieben:

**Comment by ChuckIrvine** [comment]
I've done a little testing. Does this look like a valid blot?:

```
"{\"ops\":[{\"insert\":\"testing\\n\"}]}"
```

I've never been able to find examples of what blots look like.

**Comment by KillerCodeMonkey** [comment]
Jep, you can Check Out my advanced example in the readme There you get a
live Demo with some Outputs of content Objects

Am Mo., 21. Jan. 2019, 17:47 hat Chuck <notifications@github.com>
geschrieben:

**Comment by ChuckIrvine** [comment]
Actually, I’m the guy that created the pull request with all of the examples implemented as Angular components. I don’t believe there was a json formatted example. Correct? I just updated my code to include such an example.

**Comment by KillerCodeMonkey** [comment]
Yeah json and object is not that much different... Only the json stringify
and parse step... So to get an Idea how blots Look Like IT IS enough to see
them There ;)

Am Mo., 21. Jan. 2019, 17:53 hat Chuck <notifications@github.com>
geschrieben:
