### ISSUE TITLE
i want quill-mention use in ng-quill.

### ISSUE THREAD

**Issue by Usama-Ibex** [KillerCodeMonkey/ng-quill#174]
hi
it's possible quill mention use in ng-quill.

**Comment by KillerCodeMonkey** [comment]
yes, why not. use it if you want. add the mention script and pass it as module to the modules-binding of the quill editor component.

**Comment by KillerCodeMonkey** [comment]
here is my example file:

https://github.com/KillerCodeMonkey/ng-quill/blob/master/demo.html

where you see, how the "modules" config can be used. 
For example use the quill-mention example modules config:
https://github.com/afconsult/quill-mention#example
