### ISSUE TITLE
Toolbar at the bottom

### ISSUE THREAD

**Issue by loonydevil** [KillerCodeMonkey/ng-quill#177]
Hello, I'm trying to figure out how to place snow theme toolbar at the bottom of editor. Is it possible? I found `customToolbarPosition` in readme but there's no examples how to use it and I'm confused if it's stilll used as I don't see any refs to it in repo. Thanks!

**Comment by KillerCodeMonkey** [comment]
Just Checkout my advanced demo linked in the readme. There is an example
with a toolbar positionated at the bottom of the Editor.

You can find the Code in this Repo in the Demo.html File.

Greets and good night from Germany :)


loonydevil <notifications@github.com> schrieb am Do., 23. Mai 2019, 15:17:

**Comment by KillerCodeMonkey** [comment]
```html
<h3>ng-quill - custom toolbar (position: bottom)</h3>
<ng-quill-editor
  ng-model="title"
  placeholder="''"
  custom-toolbar-position="bottom"
></ng-quill-editor>
```
