### ISSUE TITLE
Hardcoded quill.js link in snow theme

### ISSUE THREAD

**Issue by loonydevil** [KillerCodeMonkey/ng-quill#179]
Sorry if I'm asking something obvious but I see the link placeholder hardcoded as https://quill.js. Is there a way to configure it? I see it as `data-link` in their code:
```
SnowTooltip.TEMPLATE = [
  '<a class="ql-preview" rel="noopener noreferrer" target="_blank" href="about:blank"></a>',
  '<input type="text" data-formula="e=mc^2" data-link="https://quilljs.com" data-video="Embed URL">',
  '<a class="ql-action"></a>',
  '<a class="ql-remove"></a>',
].join('');
```
but not sure how to better fix it.

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/2485

seem like you have to create a custom theme base on snow theme and overwrite the template.

But i am not a quilljs expert :D
