### ISSUE TITLE
max-length and min-length attributes does not work properly for non-empty model

### ISSUE THREAD

**Issue by rumartcer** [KillerCodeMonkey/ng-quill#180]
Hello! `maxlength` and `minlength` validation does not work properly if length of initial value is invalid. `$valid` flag in `ngModelController` is true and `$error` object is empty. But it's wrong behavior as it differs from usual input field. If I change `ngModel` value in quill - validation starts working. This is only about ng-quill's `maxlength` and `minlength` validation. For example `required` validation works well. [Example in plunkr](https://plnkr.co/edit/EMlWU5xviXwcJ1hXqFC3).

**Comment by KillerCodeMonkey** [comment]
should be fixed in 4.5.1.

there was a missing `validation` call after the editor gets init and initial content set.
