### ISSUE TITLE
Quill editor content is not equal to ngModel value after pasting unsupported content into quill

### ISSUE THREAD

**Issue by rumartcer** [KillerCodeMonkey/ng-quill#188]
Hi! I've found an interesting bug. After pasting illegal content (image, file, anything else) into Quill from clipboard and programming update of ngModel editor content and model content are not equal. [See it on Plunkr](https://plnkr.co/edit/ZtnoOUsFw5YKEkyAwfeS?p=preview): I've written steps to reproduce the bug there. My real use case - catching files pasting and further processing them outside quill.

**Comment by KillerCodeMonkey** [comment]
i can not reproduce this issue.

Pasting an image works, but what do you expect when you set the format to text?
type text does not contain any html content, so images are stripped?

Just change your format to html and use $sanitize service to trust the resulting html before binding it to a dom node

PS: When i use a file (not an image) and paste it the file name is pasted ;)

**Comment by rumartcer** [comment]
> Pasting an image works

How have you done it? :smile: I can't paste image/file/screenshot neigther on your demo page nor in my plunk. Note that I don't copy formatted text with images from browser. I just copy a file from file system and paste it into quill without using quill's toolbar.

> what do you expect when you set the format to text?

When I copy formatted text with images, links and other content from browser I expect only text to be pasted. And it works. When I copy image or file from file system or take a screenshot I expect nothing to be pasted and quill not reacting on my actions. But it does not work. Visually nothing changes and it is working as expected. But internally ng-quill sets `editorChanged` variable to true, and during next `$onChanges` hook `editor.setText()` method won't be called: `if (!editorChanged) {...}` condition is false.

P.S.
If I paste file (as well as image) - nothing is pasted. No file name there.

P.P.S
In the Plunkr I demonstrate very simple flow, my real world use case is more difficult (you might see it in many messengers such as Telegram, Slack etc.):
1) User types a message (for input I use quill with ng-quill as a wrapper for AngularJS);
2) User takes a screenshot / copies file from file system in order to attach it to the message;
3) User pastes the file. Quill doesn't need to react on it, because I handle file pasting in another piece of code, that opens modal window and clears field bound to ngQuillEditor. **But value in quill input area would not be cleared when model value has already been cleared.**

**Comment by KillerCodeMonkey** [comment]
okay... but i think i do not understand the problem.

Default Quill handles pasting images and there is even an image tooltip to add images to the content.

It sound like a problem you create in your special usecase.
Did you tried the same with the plain quill editor?

Or a full example to demonstrate the real problem would be nice.

check out https://killercodemonkey.github.io/ng-quill/demo.html
there is an editor where you can change the model via a button click.

File and Image drag and drop/copy paste only works in firefox.
So this behaviour is different in each browser.

But adding an image "the quill way" by clicking on the toolbar icon for it and choose an image works everytime.

And this is what i support.

**Comment by rumartcer** [comment]
I've performed a more serious research and found a more simple case, when model and Quill's text are not equal. Here's a quiet simple [plunk](https://plnkr.co/edit/rFWeQak9ceHERmhZOpFc?p=preview). Steps to reproduce:
1. Select a text and format it using Quill's toolbar. For instance, make it bold, italic or both, that doesn't really matter
2. Press "Erase the model" button. Model is empty, but Quill's text hasn't changed. Now you can click the button as many times you want, nothing is changing.

`text-change` is triggered, but model is not changing and `$onChanges` is not called. In fact, pasting image from clipboard is the same usecase. Formatting is just a little bit representative. It's important that I can use only text as output data: json, object and html don't suit my purposes.

**Comment by KillerCodeMonkey** [comment]
feel free to send me an pr :)

**Comment by KillerCodeMonkey** [comment]
released in 4.5.3
