### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by aldymadani** [KillerCodeMonkey/ng-quill#191]
Right now my project is using Angularjs 1.2.0. Which version of ng-quill and quill that supports Angularjs 1.2.0 and supports getHTML function since I need the raw HTML from the text editor. Right now I'm combining the quill version 1.0.2 and ng-quill 1.4.2, it works fine with the configuration from the latest version, but because I use the new configuration, there will be an error which is setHTML is not a function. Therefore I need to know which version is compatible, Thank you.
![image](https://user-images.githubusercontent.com/33458423/65321515-fc117e80-dbd6-11e9-994e-7c21b04c759a.png)

**Comment by KillerCodeMonkey** [comment]
You do Not Need get and setHtml.

Just use ngModel and Pass a HTML String.

NgQuill should Transform IT to valid quilljs content.

If You Change Something in the Editor is Set to the ngModel.

And You can grab the HTML content from the
OnContentChanged callback/Output.

aldymadani <notifications@github.com> schrieb am Fr., 20. Sep. 2019, 12:47:

**Comment by KillerCodeMonkey** [comment]
and by the way... i will never support angularjs 1.2 which is 6 or 7 years old Oo...

just update to min 1.5.x.
