### ISSUE TITLE
Font-sizes not working

### ISSUE THREAD

**Issue by benwinding** [KillerCodeMonkey/ng-quill#193]
The font sizes don't seem to work in the editor, they're not working in the demo on your site either: 

https://killercodemonkey.github.io/ng-quill/demo.html#Custom%20font%20sizes

How would I go about fixing this?

Thanks for the package, really makes working with quill a dream in Angular :+1:

**Comment by KillerCodeMonkey** [comment]
hey i think they are working. this is only a "hacky" result of using multiple editors on one page.

And the custom font-sizes are colliding with the default once i think.
Removed the custom font sizes example and now the font size selection is working again.
