### ISSUE TITLE
can not display successfully

### ISSUE THREAD

**Issue by chenguanbo** [KillerCodeMonkey/ng-quill#210]
### it worked ago,but now it show as below:
![image](https://user-images.githubusercontent.com/32798314/69737226-fe5ffe00-116e-11ea-8980-8263bb07e376.png)

### what i do:
i add another editor: tinymce in another component.

### my env:
    "@angular/animations": "^7.1.4",
    "@angular/cdk": "^7.1.4",
    "@angular/common": "^7.1.4",
    "@angular/compiler": "^7.1.4",
    "@angular/core": "^7.1.4",
    "@angular/forms": "^7.1.4",
    "@angular/http": "^7.1.4",
    "@angular/platform-browser": "^7.1.4",
    "@angular/platform-browser-dynamic": "^7.1.4",
    "@angular/router": "^7.1.4",

    "ng-zorro-antd": "^7.0.0-rc.3",
    "ngx-quill": "^4.5.0",
    "quill": "^1.3.6",
    "tinymce": "^5.0.3",

in index.html , i add the link 

link href="https://cdn.quilljs.com/1.2.2/quill.snow.css" rel="stylesheet"

**Comment by KillerCodeMonkey** [comment]
but this error occurs, when the styles are not loaded correctly... aaaand you are using ngx-quill and not ng-quill (this repo).

And there you can just checkout the ngx-quill demo repo. 

global quill styles are added to the angular.json

**Comment by chenguanbo** [comment]
> but this error occurs, when the styles are not loaded correctly... aaaand you are using ngx-quill and not ng-quill (this repo).
> 
> And there you can just checkout the ngx-quill demo repo.
> 
> global quill styles are added to the angular.json

emmm... sorry! I need to donate my eyes...

it work after use ther angular.json!

Thank you !
