### ISSUE TITLE
 rel="noopener noreferrer" on links when text is processed with ng-quill

### ISSUE THREAD

**Issue by Cavayman** [KillerCodeMonkey/ng-quill#213]
Hi there, facing strange behaviour with ng-quill. 
I have text that includes links with already added attributes  rel="noopener noreferrer". 
When I try to edit somehow that text, ng quill removes all those attributes from links. 
The issue that I am facing because of this behaviour: 
I see different text length when editing that decreases after I add some charts. 

I am using snow theme and found that issue with quilljs, but it was fixed in 1.3.7 as I understand.

**Comment by Cavayman** [comment]
I am using "ngx-quill": "7.3.2", also have "quill": "1.3.7"

**Comment by KillerCodeMonkey** [comment]
then you should open this issue on ngx-quill ;-).

I have to special handling. i use the quill js api when content gets passed to the component.
