### ISSUE TITLE
Set Optional Data via Formly

### ISSUE THREAD

**Issue by deshario** [KillerCodeMonkey/ng-quill#228]
I wanna set placeholder or extra optional data from formly .... [Angular 1]
I set custom value to `editor.options.placeholder` but its not working ... What is missing from me ? Thankx

<img width="870" alt="formly" src="https://user-images.githubusercontent.com/11426727/75844177-d0dabe80-5e07-11ea-8783-3e97fc6456fe.png">

![output](https://user-images.githubusercontent.com/11426727/75844307-34fd8280-5e08-11ea-88f7-b0f1cd398318.png)

Logs
`placeholder 1 :  halo`
`placeholder 2 : newplaceholder`

**Comment by KillerCodeMonkey** [comment]
i think one issue issue is enough ...
