### ISSUE TITLE
Came here to deliver kudos

### ISSUE THREAD

**Issue by tbone849** [KillerCodeMonkey/ng-quill#240]
Was browsing for editors and found this one. I have never visited a github repo that has broad usage with 0 issues pending. That is impressive. You have gained one user today.

**Comment by KillerCodeMonkey** [comment]
do you use ng-quill or ngx-quill? 🙃

**Comment by tbone849** [comment]
Came to use ng-quill. Not a Angular > 2 fan to be honest. I know it is a lot more modular but Angular 1.x is just simpler to use and more intuitive. Going to try and implement ng-quill into my nfl mock draft site to write/deliver articles. Glad I found your project!
