### ISSUE TITLE
On-Content-Changed event firing on load

### ISSUE THREAD

**Issue by pmartijena** [KillerCodeMonkey/ng-quill#242]
Hi,

The on-content-changed event is firing on load when wrapped in an ng-if and surprisingly even an ng-show. 

![image](https://user-images.githubusercontent.com/9121102/83358058-c1074380-a33e-11ea-97bf-a27c352fbb87.png)

(for some reason github didn't want to show my code insert, sorry)

This fires changed() as soon as it's created, and then changed() when I actually type in it. This is a problem because I'm making an API call based on the change. It seems that loading the data itself is firing the changed event.

I'm using the latest AngularJS version (1.7.9)

**Comment by KillerCodeMonkey** [comment]
did you overwrite the trackChanges property in the config?
which ng-quill version do you use?

**Comment by pmartijena** [comment]
No, I didn't. I am using the latest version.

**Comment by KillerCodeMonkey** [comment]
i will close this. angular team has extended the lts period to end of this year (it was 1st july). But since it is angularjs. i will close this issue and mark the repo as readonly
