### ISSUE TITLE
Is there a way to initialize the ng-quill content before it is there in the DOM

### ISSUE THREAD

**Issue by vedika1234** [KillerCodeMonkey/ng-quill#245]
My editor tag lies under the ng-if condition. So the value is not getting initialized. Can I somehow access the `editor` beforehand

**Comment by KillerCodeMonkey** [comment]
i do not think so, because the editor needs a real dom reference. with ngIf there is none so the initialization is only possible if it is somehow connected to the dom.

maybe just use ngShow?
