### ISSUE TITLE
Any way to focus quill editor onLoad? 

### ISSUE THREAD

**Issue by kotAPI** [KillerCodeMonkey/ng-quill#246]
I've tried looking/reading through the docs to see if this is possible, is there a way to do this?

**Comment by KillerCodeMonkey** [comment]
listen on the event, when the editor is initialised and then grab the editor instance of the event data and call the `focus` function.

https://github.com/KillerCodeMonkey/ng-quill#callbackoutputs - on-editor-created
https://quilljs.com/docs/api/#focus

**Comment by kotAPI** [comment]
@KillerCodeMonkey awesome, thanks
