### ISSUE TITLE
ngQuill toolbar disappear with MD-DIALOG

### ISSUE THREAD

**Issue by OliverArthur** [KillerCodeMonkey/ng-quill#46]
When using ngQuill in a md-dialog the toolbar disappears when you open the modal

**Comment by KillerCodeMonkey** [comment]
maybe similar to #38

**Comment by OliverArthur** [comment]
Hi @KillerCodeMonkey , Yes i think is similar to #38  but in the end I was not available to use the ngQuill inside the md-dialog

**Comment by KillerCodeMonkey** [comment]
Any updates? if not i close this issues and you can try ng-quill 2.0.1 or if you are using angular2 the total new ng2-quill component.

**Comment by KillerCodeMonkey** [comment]
There is a new release v1.5.4 with ng-quill 0.20.1 with a possible fix.
