### ISSUE TITLE
settingInitValues is true if there is no content at start

### ISSUE THREAD

**Issue by zacol** [KillerCodeMonkey/ng-quill#47]
I've got a problem with `settingInitValues` on ngQuill editor init. 

If value in ngModel is not empty, everything works fine. The problem occures when ngModel is equal to an empty string and after editor init, `settingInitValues` is still set on true. It means that when you type first letter, editor think that this is an init change and doesn't trigger ngChange.

It's a part of code for function that is trigger on `text-change` event:

``` javascript
if (settingInitValues) {
   settingInitValues = false;
   return;
}
```

In fact, `text-change` event isn't even fired so there is no possibility to init editor in right way. In my solution I just removed this if statement and I don't see bad effect. I know that is not good solution but it works for now ;)

**Comment by Cordobo** [comment]
I can confirm this problem - uncommenting line 252

`settingInitValues = true;`

fixed an issue I had with Copy & Paste on an editor initialized with an empty string.
I add a PR after I have tested this for a while

**Comment by KillerCodeMonkey** [comment]
is there the chance for a pull request? if not i will close issues for 0.20.1 --> please use ng-quill 2.0.1

**Comment by Cordobo** [comment]
I use a fork for production right now but I won't add a PR. although we had no side effects so far.

Thanks for V2!

**Comment by KillerCodeMonkey** [comment]
okay then i will close this issue.. maybe you can switch to v2. If this issue occurs there, too --> open a new issue for that. Thanks and happy using quilljs :D
