### ISSUE TITLE
Which version uses angular <1.5.x ?

### ISSUE THREAD

**Issue by feruzm** [KillerCodeMonkey/ng-quill#65]
I wonder if you have any version using older angular and have it as directive not component?

**Comment by KillerCodeMonkey** [comment]
Ngquill 1.4.4 uses angularjs 1.4.7

Check out tags to dig into the code

**Comment by feruzm** [comment]
Thanks @KillerCodeMonkey !

I have tried it with latest quill version, some icons doesn't seem to work and show.
It could be really helpful to know what version of quill 1.4.4 is using?

Also, latest release of ng-quill... could this be ported to older angularjs like 1.4.x or 1.5.3.... because some of the libraries I use is dependent to older versions...

thanks

**Comment by KillerCodeMonkey** [comment]
Hey,

like i said you can find it out by yourself:
https://github.com/KillerCodeMonkey/ng-quill/blob/1.4.4/package.json

All releases are tagged in git:

<img width="159" alt="bildschirmfoto 2016-11-25 um 10 09 34" src="https://cloud.githubusercontent.com/assets/2264672/20619948/64861d9c-b2f7-11e6-9d93-3af4769f76bf.png">
<img width="327" alt="bildschirmfoto 2016-11-25 um 10 09 41" src="https://cloud.githubusercontent.com/assets/2264672/20619950/64a1fd8c-b2f7-11e6-8e63-b9da72338be0.png">
<img width="406" alt="bildschirmfoto 2016-11-25 um 10 09 57" src="https://cloud.githubusercontent.com/assets/2264672/20619952/64c0a07a-b2f7-11e6-9932-9fde8c5a00a4.png">

**Comment by feruzm** [comment]
Thanks a bunch, Bengt! Appreciate the effort!

**Comment by KillerCodeMonkey** [comment]
no probs and have a nice day ;)
