### ISSUE TITLE
New Release Readonly change not working

### ISSUE THREAD

**Issue by diwanoli** [KillerCodeMonkey/ng-quill#66]
[#65]) Hi , I am working ng-quill latest version . read-only property working based on initial value if i change read-only dynamically , read-only property not working properly

        <input type="checkbox" ng-model="readOnly">
        <ng-quill-editor ng-model="title" required="true" read-only="readOnly" modules="{toolbar: false}"></ng-quill-editor>

**Comment by KillerCodeMonkey** [comment]
I do not know if quill provides this in general:
http://quilljs.com/docs/configuration/

i only found that i can set it initially for creation.

do you know another way? 
If not you have to could add two quill with the same model --> with *ngIf you can destroy the editable one if readonly and vice versa

If this workaround solves the issue or you do not know another approach, close the issue please.

**Comment by diwanoli** [comment]
Thanks ,  Giving workaround fix . I am also trying to fix readonly property other way around.

**Comment by KillerCodeMonkey** [comment]
But i think it is cleaner and easier if your grad the editor instance with the editorcreated output from ng2-quill and call the quill function directly, if you need them, instead of adding additional bindings?

**Comment by KillerCodeMonkey** [comment]
i added it anyway and released 2.0.1
