### ISSUE TITLE
ngQuill model didnt update when we are changing Link value

### ISSUE THREAD

**Issue by diwanoli** [KillerCodeMonkey/ng-quill#67]
Hi 
   When we change link value in the link dialog box, It didn't update the model value .

**Comment by KillerCodeMonkey** [comment]
should be fixed in new release 2.0.2 ;).

Thanks for testing and reporting

**Comment by diwanoli** [comment]
Hey , I have found the quill providing text-change event with source . It might help for fixing this issue
https://quilljs.com/docs/api/#text-change
quill.on('text-change', function(delta, oldDelta, source) {
  if (source == 'api') {
    console.log("An API call triggered this change.");
  } else if (source == 'user') {
    console.log("A user action triggered this change.");
  }
});
