### ISSUE TITLE
Color formatting whitelist makes it nonfunctional

### ISSUE THREAD

**Issue by eghernqvist** [KillerCodeMonkey/ng-quill#72]
Coloring works fine without any whitelisting but as soon as I add whitelisting configuration the button does nothing, no errors in console or events fired. Other functions work fine.

Using version 2.0.0

Here's my attempted configuration:
```
app.config(['ngQuillConfigProvider', function (ngQuillConfigProvider) {
  // var toolbarOptions = ['bold', 'italic', 'underline', 'blockquote', 'link', 'color', 'align', 'direction', 'image'];
  var toolbarOptions = ['color'];
  ngQuillConfigProvider.set({
    toolbar: toolbarOptions
  }, undefined, 'Placeholder', toolbarOptions, document.body, false);
}]);
```

Cheers

**Comment by KillerCodeMonkey** [comment]
Could you check this with plain QuillJS? I sadly have to say (for my shame) i did not use Quill, yet. And i am using the default quilljs functionalities to create the editor.

**Comment by KillerCodeMonkey** [comment]
a got it --> you need to specify the colors you want to have:
http://quilljs.com/docs/modules/toolbar/ search for "color" --> if you want all default colors:

```
var toolbarOptions = [{'color': []}];
```

**Comment by eghernqvist** [comment]
Used 
```
toolbarOptions = [{'align': []}, {'color': []}];
```
now and this fixes the dropdown not showing but when selecting a color the text gets deselected, causing the text to not get any color applied to it. Same for alignment.

Selecting color first and then typing does nothing either. 

QuillJS version 1.1.5 and ng-quill version 2.0.2

**Comment by eghernqvist** [comment]
Fixed by having two different arrays since the `formats` array can't process the array with `{'color': []}` type values in it.

Working example:
```
app.config(['ngQuillConfigProvider', function (ngQuillConfigProvider) {
  var toolbarModules = ['bold', 'italic', 'underline', 'blockquote', 'link', {'align': []}, {'color': []}];
  var toolbarFormats = ['bold', 'italic', 'underline', 'blockquote', 'link', 'align', 'color'];
  ngQuillConfigProvider.set({
    toolbar: toolbarModules
  }, undefined, 'Placeholder', toolbarFormats, undefined, undefined);
}]);
```

**Comment by KillerCodeMonkey** [comment]
Nice you get it to work. Sorry again, i am not the quill pro :) and i do Not know how to configure it in Detail.
