### ISSUE TITLE
Defaults are not changing on the top

### ISSUE THREAD

**Issue by shadow1349** [KillerCodeMonkey/ng-quill#73]
When I am changin properties in the text editor, lets say I am changing a piece of text from Normal to Heading 1, when I do that and I drop down the Headings in the menu it still thinkgs that the selected text is on Normal. It is still on Heading 1 in the editor, but the menu item does not register that change and it thinks the default is selected.

I downloaded the zip and just ran that and thats one of the issues that I ran into.

This issue is replicated with pretty much all of the menu properties you can set.

**Comment by KillerCodeMonkey** [comment]
do not know, what you are doing works like charme

Tested with my demo page here --> look at the selected text "!!!", color, background, font, font size.. is working
<img width="985" alt="bildschirmfoto 2016-12-14 um 23 18 51" src="https://cloud.githubusercontent.com/assets/2264672/21203686/d9511c10-c253-11e6-84a8-bc2b3d72416c.png">

**Comment by shadow1349** [comment]
Changing text and stuff works just fine, however changing it back is where I had issues. So once you made the !!! a different color, try changing it back to black.

I think this is a quill issue, because I had the same issue with the editor on the quill page.

**Comment by KillerCodeMonkey** [comment]
Strange, because on my system macos sierra and firefox, chrome, safari this works, too

**Comment by shadow1349** [comment]
I'm using chrome on Windows 10. When I go to http://quilljs.com/docs/formats/ and I type in 'test text' then I change the color of 'text' to red. When I try to change the color of 'text' back to black it thinks that it is already set to black and won't change so I'm stuck with red text.

**Comment by KillerCodeMonkey** [comment]
you are right - there i have the problem, too. But in my demo: http://killercodemonkey.github.io/ng-quill/demo.html it is working for me. My demo is using QuillJS 1.1.5 and not the current 1.1.6

So maybe this is the problem.

**Comment by shadow1349** [comment]
Ahhhhh yea I was using a newer version, I'll try and use quill 1.1.5

**Comment by shadow1349** [comment]
Yep that fixed it. Thank you!
