### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by destpat** [KillerCodeMonkey/ng-quill#74]
i have an error Uncaught SyntaxError: Unexpected token import quill.js:1
`import Quill from './core';`

**Comment by KillerCodeMonkey** [comment]
i think this has nothing to do with ngquill, because it is an error in Quill.js.

How did you install quill and ng-quill?

**Comment by destpat** [comment]
i use cdn for quillJs, and i have installed ng-quill by bower install

**Comment by destpat** [comment]
I found my error, i think it's because i have call two times quillJs, once with bower and once with external CDN. 

Thank you
