### ISSUE TITLE
Callback not working

### ISSUE THREAD

**Issue by ankitjs** [KillerCodeMonkey/ng-quill#76]
Hi,
Thanks for such great component, I have tried to call function on content changed as mentuioned in docs "on-content-changed="myCallback(editor, html, text)" and in my Controller is $scope.myCallback = function(x,y,z){ ... }.
another thing can you share fiddle/plunker for ng-quill vaidation (required) inside form.
Thanks

**Comment by KillerCodeMonkey** [comment]
You can simply take a look at my demo page:
https://github.com/KillerCodeMonkey/ng-quill/blob/develop/demo.html

and the live preview:
http://killercodemonkey.github.io/ng-quill/demo.html

There is also an example with the contentChanged callback --> which is working. open the demo and open JS-Console --> Type something in the first editor.

<img width="712" alt="bildschirmfoto 2017-01-05 um 13 34 37" src="https://cloud.githubusercontent.com/assets/2264672/21680723/c30cf556-d34b-11e6-9c31-a5a98091aeb3.png">

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
close due to inactivity of issue creator

**Comment by ankitjs** [comment]
Hi,
Thanks for your response and sorry I was busy on some other issue,couldn't revert back. I checked your example :
[https://github.com/KillerCodeMonkey/ng-quill/blob/develop/demo.html], but no luck, here are screen shots 
(a) template
![quill1](https://cloud.githubusercontent.com/assets/20476475/22063919/4b95c172-dda7-11e6-92b3-d75c753d2b55.png)
(b) controller
![quill2](https://cloud.githubusercontent.com/assets/20476475/22063927/54bbac8a-dda7-11e6-9373-87a45a52ef9a.png)
(c) output
![quill3](https://cloud.githubusercontent.com/assets/20476475/22063941/5eaf82de-dda7-11e6-9851-7ca03ee89a98.png)

even I tried your example, but no luck. 

thanks

**Comment by KillerCodeMonkey** [comment]
you are registering two on-content-changed callbacks.

And the visibility of the scope is correct?

**Comment by ankitjs** [comment]
"you are registering two on-content-changed callbacks." 
I was checking, even tried with 'on-content-changed', but no luck.
"visibility of the scope is correct", 
yes

**Comment by KillerCodeMonkey** [comment]
could you give me access to you project? then i will take a deeper look at it.

I added testcases in the last days to this project and the callbacks are working there as expected, too.

thank

**Comment by jziggas** [comment]
I seem to be in a similar situation. on-editor-created is not working but on-content-changed is working. It's very confusing. Still troubleshooting - will report back if I find anything.

**Comment by jziggas** [comment]
So I'm actually wrapping ng-quill with my own directive, and I'm wondering if this is why I'm not seeing my scope when `this.editorCreated` is called from within ng-quill:

> $postLink() - Called after this controller's element and its children have been linked. Similar to the post-link function this hook can be used to set up DOM event handlers and do direct DOM manipulation. **Note that child elements that contain templateUrl directives will not have been compiled and linked since they are waiting for their template to load asynchronously and their own compilation and linking has been suspended until that occurs.**

**Comment by jziggas** [comment]
`this.editorCreated` is called before the linking function of my directive is called.

**Comment by KillerCodeMonkey** [comment]
Could you show me your code?

**Comment by jziggas** [comment]
Perhaps privately in a gist. We've moved onto ckeditor now, but I'll checkout the old branch when I get a chance and hit you up via email.

**Comment by KillerCodeMonkey** [comment]
thanks for the response. i close this issue. But feel free to email me.

**Comment by mindscratch** [comment]
@KillerCodeMonkey did you get any info from @jziggas?

**Comment by mindscratch** [comment]
Using angular 1.5.x, In my components controller this works:

`$scope.$on("editorCreated", function (event, editor) {
            ctrl.editor = editor;
        });
`

**Comment by jziggas** [comment]
Hi, I'm back to using ng-quill and have it wrapped in component. That scope listener is confusing if you're using a component. My wrapper component looks something like this, it uses the component lifecycle hooks:

```
angular.module('app').component('ngQuillWrapper', {
    controllerAs: 'vm',
    bindings: {
        content: '=',
        onContentChanged: '&?',
        onEditorCreated: '&?',
        onSelectionChanged: '&?',
        ...
    },
    ...
    controller: function ngQuillWrapper($element, $scope, ..., ...) {
        let vm = this;
        let editor;
        vm.editorCreated = editorCreated(_editor) {
            editor = _editor;
            ...
            if (vm.onEditorCreated) {
                vm.onEditorCreated({editor: editor});
            }
            ...
        }
    }
});
```

```
<ng-quill-editor
    modules="vm.modules"
    ng-model="vm.content"
    on-editor-created="vm.editorCreated(editor)"
    on-content-changed="vm.contentChanged(editor, html, text, delta, oldDelta, source)"
    on-selection-changed="vm.selectionChanged(editor, range, oldRange, source)"
    toolbar="true"
    ...
>
...
```
