### ISSUE TITLE
Titles for buttons

### ISSUE THREAD

**Issue by CHR15-** [KillerCodeMonkey/ng-quill#77]
Is it possible for titles to appear on the action buttons, i.e hovering 'B' would reveal 'Bold'?

**Comment by KillerCodeMonkey** [comment]
Hey there!

You have to check QuillJS documentation for that. I do not intruduce anything new. I am using the default way to create the editor instance.

So everything you can configure for Quill, you can pass to the `modules`, `formats` property.

If this is not possible with quill --> create a feature request there.
