### ISSUE TITLE
Setting length for quill editor

### ISSUE THREAD

**Issue by ankitjs** [KillerCodeMonkey/ng-quill#78]
Hi 
Is there any options, to set text-limit for the editor. For example if there is any sceneraio which allow users to enter only 2000 or 4000 charcters limit or word limit e.g. 500-800 words.
I tried to make my own custom directive to update model, it properly set model but not for text editor is not set.
Just for a quick test(to check if restricting ng-model value will affect text-editor view value or not), I tried to restrict my modal to only numbers, I entered 'Abc7', it still shows 'Abc7' in text-editor(view-value) but my ng-model contains '7' because of my directive restricting it to numbers only.

so is there any support for character/word limit??
Thanks

**Comment by KillerCodeMonkey** [comment]
not per default.

Here are some ideas:
https://github.com/quilljs/quill/issues/688

**Comment by KillerCodeMonkey** [comment]
Die Frage ist auch, was passieren soll --> soll eher der status gesetzt werden, dass das input feld invalide ist, oder soll es direkt nicht möglich sein, mehr als die gesetzten Zeichen einzugeben?

**Comment by KillerCodeMonkey** [comment]
added min- and maxlength support in newest version.

It will add validation state and classes.

**Comment by ankitjs** [comment]
Thanks, for your response.
[https://github.com/quilljs/quill/issues/688](url)
the solution provided, is a call back on the quill referece we using and the component you provided is a wrapper for quill editor.

**Comment by ankitjs** [comment]
"Cut off the other chars or set the model as invalid, so you can style it like 'invalid'", I believe, cutting the characters will work like normally happens in textarea, instead of setting model as invalid.
Former will be visible to user, because it will cut off and latter would be on form submit or on interaction with model(depends).
Thanks

**Comment by KillerCodeMonkey** [comment]
not to force a functionality like cutting off, i set the control as invalid (ng-invalid) class is added. So if you put ng-quill in a form, the form will be invalid.

Cutting off is maybe an unwanted behavior. So if you get the `on-content-changed` callback working, you can cut it off on your own very easy.

**Comment by ankitjs** [comment]
seems nice solution, when to expect next update of this feature ?
thanks

**Comment by KillerCodeMonkey** [comment]
it is already there for 2 days ( ^^ ).
v2.2.0

**Comment by ankitjs** [comment]
Thanks
