### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ng-quill#80]
Migrating from Quill 0.2 to 1.0 (and thus ng-quill) and I'm seeing this `translations= ...` attribute in my code but no documentation or reference to it anywhere in your repo. Did there used to be a translations property or am I just going crazy?

**Comment by KillerCodeMonkey** [comment]
no translations, yet. QuillJS 1.0 has the new bubble theme and so on and it initialises everything on its own. There is the possibility to build a custom toolbar with own html and so on. But i do not want to go this way. 

https://quilljs.com/docs/modules/toolbar/

It would be nice if you could pass translations to each format + a title-tag text.

Maybe you have an idea how to solve this.

**Comment by jziggas** [comment]
Hmmm ...

It does looks like building a custom toolbar is what jhchen had in mind in [209](https://github.com/quilljs/quill/issues/209). His responses are even more unhelpful in [1192](https://github.com/quilljs/quill/issues/1192). I'll need to think about this because localization is a requirement on my project. A custom toolbar module might not be so bad if we interpolate the translated values. Manipulating CSS seems like the only other option and that's a worse alternative IMO.

**Comment by KillerCodeMonkey** [comment]
yeah i was hoping there will be something like i18n because it was promoted last year for the featuers of quilljs 1.0.

I could provide something like that and make ugly dom-manipulation to solve this.

Maybe this is something for you like a workaround --> add you translation with javasceript --> select the formats and add text or innerHTML to the option-tags and so on?

**Comment by jziggas** [comment]
Yeah that sounds reasonable. I'm not sure but the CSS styles might have to be manipulated as well to get the tooltips.

After speaking with my team today we are leaning towards switching to CKEditor because of its language support (among some other things like IE10). Going to experiment with that over the next couple days.

If we decide to continue using Quill though I'd be interested in continuing to contribute to this project :) Could try to help with a translation feature if that happens.

**Comment by KillerCodeMonkey** [comment]
Hehe. Feel free to contribute ;). 
Hmm good old CKEditor i used it a few years ago with custom plugins and so. But it was hell ... and pleeeeease do not activate html-editing for the endusers ...

The advantages of quill are the simplicity of the editor itself. It uses modern technology and has an own representation of the content --> not html! So it is super easy to create own plugins -> upgrade  or change plugins without hacky html-patches ;)

I will not close the issue. Maybe you have an idea to solve this or maybe we get some more info from Jason Chen.

**Comment by KillerCodeMonkey** [comment]
@jziggas i asked json and he replied with the following

```
You can now set the picker label in the HTML markup. This example adds custom fonts but does demonstrate you can pick whatever label you want for the picker: http://quilljs.com/playground/#custom-fonts. You always could supply your own button and Quill would attach the appropriate listeners so on those two fronts I do not see an issue with regards to internationalization anymore.

There are still a couple limitations in the tooltip whose text is still not customizable. The only reason why is the same reason for the picker labels previously: it takes work and someone needs to do it and so it's just a matter of prioritization and someone willing to contribute.
```

**Comment by KillerCodeMonkey** [comment]
So as an explanation: 

You can create your own toolbar like an own compontent with your own labels and values like this:

```
<div id="toolbar-container">
  <select class="ql-font">
    <option selected>Aref Ruqaa</option>
    <option value="mirza">Mirza</option>
    <option value="roboto">Roboto</option>
  </select>
</div>
```

After that you can pass your module config to ng-quill: 

```
{
    toolbar: '#toolbar-container' // use your own toolbar instead of the default one
}
```

QuillJS adds everything else on its own like in this example with two custom fonts:
http://quilljs.com/playground/#custom-fonts

But in this way you can create your own toolbar with own labels and translations with existing Quill formats, too.

**Comment by jziggas** [comment]
It seems like you can't just pass in a string or angular element this way, have you tried this? I just tried these two ways:
```
app.config(function(ngQuillConfigProvider) {
    let toolbar = `
        <div id="toolbar-container">
            <select class="ql-font">
                <option selected>Aref Ruqaa</option>
                <option value="mirza">Mirza</option>
                <option value="roboto">Roboto</option>
            </select>
        </div>
    `;
    ngQuillConfigProvider.set({
        toolbar: toolbar
    });
});
```

and also wrapping with `angular.element`:

```
let toolbar = angular.element(`
        <div id="toolbar-container">
            <select class="ql-font">
                <option selected>Aref Ruqaa</option>
                <option value="mirza">Mirza</option>
                <option value="roboto">Roboto</option>
            </select>
        </div>
    `);
```

Which makes me think it needs to be attached to the window's DOM somewhere.

**Comment by KillerCodeMonkey** [comment]
yep i know, but only css-selectors are allowed in quilljs ;)

**Comment by jziggas** [comment]
Err... So are we supposed to just give this `left: -10000px` and let it exist at all times or am I not thinking of something?

**Comment by KillerCodeMonkey** [comment]
naaa.. you want to show the toolbar to the user i think? how would he using formats without a visible toolbar.

you add the toolbar over the ng-quill-editor and pass the selector to ng-quill?

**Comment by jziggas** [comment]
> you add the toolbar over the ng-quill-editor

Can you elaborate on that? I'm not sure what you mean by adding it "over" ng-quill-editor. Not understanding where the HTML for a custom toolbar is suppose to go. Do you mean like above the component directive somewhere?

**Comment by jziggas** [comment]
Also I noticed in the Quill examples that they are providing a container for the editor itself and then referencing that:

```
<div id="toolbar">
...
</div>
**<div id="editor"></div>**

<script type="text/javascript">
var quill = new Quill('#editor', {
  modules: {
    toolbar: '#toolbar'
  }
});
```

And in your [code](https://github.com/KillerCodeMonkey/ng-quill/blob/develop/src/ng-quill.js#L151) instantiates Quill without any identifier: `editor = new Quill(editorElem, config);`. Does that make any difference?

**Comment by KillerCodeMonkey** [comment]
nope, but you can try the following:
```
 let toolbar = angular.element(`
        <div id="toolbar-container">
            <select class="ql-font">
                <option selected>Aref Ruqaa</option>
                <option value="mirza">Mirza</option>
                <option value="roboto">Roboto</option>
            </select>
        </div>
    `)[0];
```

To grab the native dom element instead of the jqLite element. Maybe this is working

**Comment by jziggas** [comment]
Alright I seem to have got it working by creating a wrapper component and putting the toolbar dom immediately above your component, so that the template looks like:

```
<div id="toolbar-container">... buttons ...</div>
<ng-quill-editor ng-model="..." modules="..."></ng-quill-editor>
```

**Comment by jziggas** [comment]
Good point on the jqLite element thanks

**Comment by KillerCodeMonkey** [comment]
woah maaan... thanks for the tip ;).

Maybe i should add a donation button to the readmes of ngQuill and ngxQuill 👯‍♂️

**Comment by dsebastien** [comment]
For those interested, I wrote a small article about this issue, detailling my approach for solving it: https://medium.com/@dSebastien/dynamically-customizing-quill-ngx-quill-editors-in-an-angular-application-b81c75bc4a6
