### ISSUE TITLE
Image only not triggering on-content-changed

### ISSUE THREAD

**Issue by CHR15-** [KillerCodeMonkey/ng-quill#81]
Hi!

Seems as if creating a new editor and then uploading an image only without editing the text causes on-content-changed to not be triggered.

Steps:

1) Create a new directive for ng-quill with a on-content-changed callback, drop a console log in there for testing

2) Without typing or adding any input to the editor, click the upload image button and select an image

3) Notice no log (callback is not triggered)

**Comment by KillerCodeMonkey** [comment]
could you check this if quill editor fires the "text-change" event ?

http://quilljs.com/docs/api/#text-change

Would be nice if you could create an editor without ng-quill --> simple quilljs

If quilljs itself does not trigger the text-change event. it is more a quilljs bug.
Let me know if you have time. If not i can check this this evening.

Thanks!

**Comment by CHR15-** [comment]
Would be much appreciated mate!

**Comment by KillerCodeMonkey** [comment]
seems to be working:

http://codepen.io/KillerCodeMonkey/pen/xgLeoR

watch the `false` above the editor --> after inserting an image it switches to `true` and you get a `console.log`
