### ISSUE TITLE
How to render ng-quill rich-text output to HTML

### ISSUE THREAD

**Issue by sinteco** [KillerCodeMonkey/ng-quill#83]
i have finally do my project with ng-quill but cant get the saved output displayed in html. i cant get documentation in how to display it in angularjs help please?

**Comment by KillerCodeMonkey** [comment]
google for ngBindHtml and keep in mind angular strips unsafe html. But therefore exists an service called $sce:

https://docs.angularjs.org/api/ng/service/$sce

there is also an example with ng-bind-html (e.g. `$sce.trustAsHtml(yourVariableWithHtml)`)
