### ISSUE TITLE
The placeholder and maxlength is not working

### ISSUE THREAD

**Issue by renilbabu03** [KillerCodeMonkey/ng-quill#84]
I don't know if i am doing it wrong..I configured it like this-->
.config(['ngQuillConfigProvider',function(ngQuillConfigProvider){
ngQuillConfigProvider.set('placeholder');
])
then i set placeholder in the template . Its not showing up...Also the maxlength is not working....Does maxlength has necessarily be in a form?? Will it(maxlength) work without a form ?

**Comment by KillerCodeMonkey** [comment]
until now you have to configure the it like this:

```
ngQuillConfigProvider.set(null, null, 'myPlaceholderText here');
```

the set function takes these arguments:

```
set = function(modules, theme, placeholder, formats, boundary, readOnly)
```

I know a config object would be better. But i do not have time to change it, yet.
But you have to set the correct parameter.

How min and maxLength is working you can see in the demo:
http://killercodemonkey.github.io/ng-quill/demo.html

The last editor setzt min- and max-length.
I also have testcases for that ;).

keep in mind this are not the html default "maxlength" and "minlength".. you need to set "max-length" and "min-length".

And yes, like in the demo --> the validation is connected to the ngModel and not with a form ;)

**Comment by renilbabu03** [comment]
Thank you for your help
