### ISSUE TITLE
Problem in new version of ngQuill

### ISSUE THREAD

**Issue by renilbabu03** [KillerCodeMonkey/ng-quill#85]
I am using latest version of ngQuill. I have all the required libraries and dependencies but still it shows the error :
'Uncaught SyntaxError: Unexpected token import '
and also 
'TypeError: Quill is not a constructor'. I don't know if i am doing it right. I have attached a image below.

![quillerror](https://cloud.githubusercontent.com/assets/18526147/22419626/6768837e-e704-11e6-84aa-5a11d0881c08.png)

**Comment by KillerCodeMonkey** [comment]
Did you include quill.js befor ngQUill in your code?

Are you using a module-loader.

Show me some code ;)

**Comment by renilbabu03** [comment]
Yes I have included quill.js before ngQuill .

**Comment by ankitjs** [comment]
I have also experience the same issue, in my project.
included quill.js before ng-quil and not used require or any other module loader.

**Comment by KillerCodeMonkey** [comment]
Okay, then i need some code or you check out the `demo.html` in the root of this repo.

**Comment by ankitjs** [comment]
Your old version of ng-quil '1.5.3' used quill '0.20.1', now latest version of ng-quill "2.0.2" use quill '1.1.5',
both quill versions has difference in directory structure as well as in code,latter uses the 'import', 
currently we are not using any module loader.
any suggestions?
thanks

**Comment by KillerCodeMonkey** [comment]
like i said... i need some code to help you.

ng-quill is completely rewritten like quilljs itself.
So it changed how you can configure ngQuill and use it.
(the demo uses 1.1.5, but you should use the latest quilljs release like 1.2.0)

It also works without any module loader and with umd/amd like requirejs now. 
For both you can find examples in the root directory.

if Quill is not found, then there is a problem with loading quilljs.

**Comment by renilbabu03** [comment]
I have checked the network and the quill and ngquill is loaded properly. 
the error shows up in import.....

![errir2](https://cloud.githubusercontent.com/assets/18526147/22422704/d8f38336-e713-11e6-87fe-a6d5cc104f29.png)

**Comment by renilbabu03** [comment]
![lskjfslkfj](https://cloud.githubusercontent.com/assets/18526147/22422776/3fc64300-e714-11e6-8a2a-1f6b8a2e22bb.png)
I don't understand why the import is showing error....

**Comment by renilbabu03** [comment]
![index](https://cloud.githubusercontent.com/assets/18526147/22422851/ab0ad72a-e714-11e6-953b-a2a880f1a983.png)
![app](https://cloud.githubusercontent.com/assets/18526147/22422881/d927b92a-e714-11e6-9813-35c5fc828f34.png)

**Comment by renilbabu03** [comment]
![jobmodule](https://cloud.githubusercontent.com/assets/18526147/22422932/1885f5fa-e715-11e6-8bbe-c29aa4e93602.png)
Here's the template i am using

**Comment by KillerCodeMonkey** [comment]
ehhm you should not use the quill.js from the root quill folder. take a look in the dist folder --> install it via nodejs and take a look in the node_modules/quill/dist folder

**Comment by KillerCodeMonkey** [comment]
Hey guys @renilbabu03 @ankitjs ,

do you solve your problem?
the quill.js in the base folder of quilljs folder is in es6 format, you need to use the correct one from the dist-folder.

If you can not solve the problems... feel free to open it again.

**Comment by SaadeMotion** [comment]
My Quill installation doesn't have the "dist" folder. The problem is in

`import './polyfill';`

**Comment by gbatchvarov** [comment]
I have the same issue. I did not install using npm. I used  "bower install ngquill --save". I got ngQuill 2.2.2, quill 1.1.5, and angular 1.5.11.
Just for the record when you install with bower - there is no dist directory under quill directory.
The error is related to the "import Quill from './core'" line. The JS engine does not like the "import" command and then everything fails after that. By the way I am running Chrome which is up-to-date.

Any suggestions?

**Comment by SaadeMotion** [comment]
@gbatchvarov i have the same issue, i cant use Npm, i really need to only use Bower for dependencies.

**Comment by KillerCodeMonkey** [comment]
Yeah, i should remove ng-quill from bower, because quill is not longer supported there.

@gbatchvarov @SaadeMotion then grab the sources from a cdn:

https://cdnjs.com/libraries/quill
https://cdnjs.com/libraries/ng-quill

**Comment by SaadeMotion** [comment]
But my project is in production, and i really need to use bower, can u just update bower package?

CDN is not a option for me :/

**Comment by SaadeMotion** [comment]
I'm using with Laravel Elixir, so it compiles all my NPM and Bower dependencies to a single `final[version].js`

I tried with npm, but it doesn't seems to work either.

I have no choice than using Bower.

**Comment by KillerCodeMonkey** [comment]
i did not removed ng-quill from bower (only the info in the readme). but i am not responsible for the quilljs package there...

And even if you are using a backend framework you can add a custom gulp or grunt task to prebundle your node_modules or copy your node_module dependencies in your assets folder.

I googled a little bit:
https://laracasts.com/discuss/channels/elixir/how-do-you-include-files-from-node-modules-in-elixir

may this helps.

**Comment by SaadeMotion** [comment]
yeah, i know that. I attempted to install ng-quill and quilljs from npm. But angular doesn't find the ngQuill injector, like it wasn't there.

**Comment by SaadeMotion** [comment]
Thanks, but with NPM package i still getting error:

`Quill is not a constructor`

**Comment by KillerCodeMonkey** [comment]
then show me how you include quill and quilljs in your project

**Comment by SaadeMotion** [comment]
It's a automated process. Laravel elixir get files from Bower then mix it in one file `final[version].js`.

My project is working on: 

Bower = dependencies to include in production.
NPM = dependencies in local env only (compilers, linters, ... ).

In module i'm using:
`angular.module('myApp', ['ngQuill']);`
then in view:
`<ng-quill-editor ng-model="message"></ng-quill-editor>`
when angular tries to render ng-quill-editor directive, it fails on: `Quill is not a constructor`.


Already tried:
Copy files from NPM then paste it in bower ng-quill folder. Did not work either.

**Comment by KillerCodeMonkey** [comment]
yeah sorry, but then you have to ask some guys with knowledges about that framework.
Sounds like QuillJS is not in the package --> not in the right order (have to be loaded before ng-quill!).

Is there an index.html somewhere? Try to add quillJS as script-tag before your final.js is loaded.

**Comment by dnlmzw** [comment]
I looked around in the QuillJS repo [Re-add built distribution for v1.0 #926](https://github.com/quilljs/quill/issues/926) where the same issue is being discussed. I managed to get a pre-built version by adding: `https://github.com/quilljs/quill/releases/download/v1.1.5/quill.tar.gz` to the Bower path, which got me a /dist folder.

Unfortunately I'm now stuck with `app.component is not a function` when I include ng-quill.

**Comment by KillerCodeMonkey** [comment]
i do not test and use bower, because it is a dying and unnecessary thing. node packages with npm or yarn is the thing to go, now. 

In most projects you need special node environments and build systems hard wired with npm.

I only bump the bower version, because someone asked some time ago.

**Comment by dnlmzw** [comment]
The error above was caused due to using an old version of angular, which I missed trying to figure out the thing above. Well - anyway, the bower stuff works now :)

**Comment by KillerCodeMonkey** [comment]
i do not test and use bower, because it is a dying and unnecessary thing. node packages with npm or yarn is the thing to go, now. 

In most projects you need special node environments and build systems hard wired with npm.
Mixing bower and npm really makes no sense. 

I only bump the bower version, because someone asked some time ago.

You should switch to use npm/yarn instead of bower --> because of that i removed the installation guide for ng-quill for bower from the readme

**Comment by dnlmzw** [comment]
Maybe some other time ;)

**Comment by DamodarSojka** [comment]
As @dnlmzw using https://github.com/quilljs/quill/releases/download/v1.1.5/quill.tar.gz works. 

It however involves few other steps so for whoever needs it:
1. bower install quill=https://github.com/quilljs/quill/releases/download/v1.2.0/quill.tar.gz --save
2. bower install ng-quill --save, here bower will ask which version of quill it should use as ngQuill will have a different version/way of stating quill as dependency, pick the version you have already installed (e-tag one, for version 1.2.0 it's e-tag:27ec07ac1)
3. Becuase of this different way of installing quill it will only load the js file, fix that by forcing the library to load the css aswell by adding this to "overrides" section of YOUR bower.json file:
```
"quill": {
      "main": [
        "quill.snow.css",
        "quill.js"
      ]
    }
```
If you intend to use theme other than snow adjust accordingly.

Now it should all work!
@KillerCodeMonkey Would you mind adding that to the README and readding the section about bower install?

**Comment by KillerCodeMonkey** [comment]
Nope. I Do Not want to spread Info about bower, because bower is obsolet im
times of node_modules and should be used.

Damodar Sojka <notifications@github.com> schrieb am Do., 11. Okt. 2018,
15:14:

**Comment by DamodarSojka** [comment]
While I agree about it being declared obsolete, a lot of software
development is about managing legacy.  Bower was downloaded close to 1.5m
times from npm last month, for reference the new and sexy yarn got 1.8m.
Open source is great as long as it serves it's users. I did all I can to
make it easier for whoever is in my situation to use your OSS. You will do
what you want with it.

**Comment by jsren** [comment]
i do not test and use JS, because it is a dying and unnecessary thing. C++ with WASM or Typescript is the thing to go, now.

In most projects you need special node environments and build systems hard wired with tsc.
Mixing JS and Typescript really makes no sense.

I only bump the JS version, because someone asked some time ago.

You should switch to use TS/WASM instead of JS --> because of that i removed the installation guide for ng-quill for JS from the readme

#copypasta

**Comment by ravisinghnath** [comment]
@KillerCodeMonkey  I have installed quill and ng-quill npm in my angular app. And copy both the files, quill.js and ng-quill.js, from node_modules (dist folder) to my local folder in my app. After that load both the files first quil then ng-quill from main js loader file.
![screenshot_3](https://user-images.githubusercontent.com/36439114/49931822-b7411480-feed-11e8-8935-3131866804f7.png)

But I got **`Quill is not a constructor`** error. I didn't know where is the issue. Please help me with that.

**Comment by KillerCodeMonkey** [comment]
check the comments in this topic. you need to include quill and the styling in your index.html before initialising your app.
Or if you use something like requirejs, you need to define it as a dependency of ng-quill

**Comment by ravisinghnath** [comment]
Here is how i use Quill in my App:

This is how my App initialing
![image](https://user-images.githubusercontent.com/36439114/49932628-819d2b00-feef-11e8-99e8-f661f79d4c85.png)

Loading js files
![image](https://user-images.githubusercontent.com/36439114/49932664-9ed1f980-feef-11e8-8069-16e5563b265e.png)

Added dependency to my app module
![image](https://user-images.githubusercontent.com/36439114/49932774-e48ec200-feef-11e8-957f-2466c8563bb8.png)

Uses
![image](https://user-images.githubusercontent.com/36439114/49932784-f1131a80-feef-11e8-89fc-322813c38965.png)

Also I have read upper comments and I am not useing requirejs.

**Comment by KillerCodeMonkey** [comment]
your screenshots does not help...
how do you load your vendors

in your `Loading js files` screenshot ?
