### ISSUE TITLE
Inline styles instead of class attribute

### ISSUE THREAD

**Issue by salacis** [KillerCodeMonkey/ng-quill#86]
Is it possible to get inline styles instead of classes like in the example below?

http://quilljs.com/playground/#class-vs-inline-style

**Comment by KillerCodeMonkey** [comment]
sure if you are using ng-quill, quilljs is a dependency and so installed with if you run `npm install`.

So you have access to "Quill" itself and register or configure own or existing modules, formats and so on.

But like in this example --> you have to build your own custom toolbar. With ng-quill you can pass the modules configuration: 

```
<div id="my-toolbar">BUILD YOUR CUSTOM TOOLBAR HERE</div>
<ng-quill-editor ng-model="myModel" modules="{ toolbar: '#my-toolbar' }"></ng-quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
@salacis did you solve your issue?
