### ISSUE TITLE
Bind options

### ISSUE THREAD

**Issue by jamielovelace** [KillerCodeMonkey/ng-quill#87]
Is it possible to bind an object of options?

E.g 
```
<ng-quill-editor theme="bubble" ng-model="body" options="myOptions"></ng-quill-editor>
```

**Comment by jamielovelace** [comment]
Ignore that, its called modules :)

**Comment by KillerCodeMonkey** [comment]
what do you mean with options?

check readme:
https://github.com/KillerCodeMonkey/ng-quill#configuration

you can set modules configuration as object and formats
