### ISSUE TITLE
Customizing Attributors

### ISSUE THREAD

**Issue by jamielovelace** [KillerCodeMonkey/ng-quill#88]
Does the module have this functionality at all? 
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors

Not too sure where i'd add this in? 
```
var FontAttributor = Quill.import('attributors/class/font');
FontAttributor.whitelist = [
  'sofia', 'slabo', 'roboto', 'inconsolata', 'ubuntu'
];
Quill.register(FontAttributor, true);
```

Sorry to be a pain :)

**Comment by KillerCodeMonkey** [comment]
simply check out this:
https://quilljs.com/playground/#custom-fonts

you add the new fonts before the usage of ng-quill e.g. at the beginning in the controller - base controller or component, where you like it.

But you need to add the correct styles in you css and build up you own toolbar with the new keys.
With ng-quill you can set:

```
<div id="toolbar-container">
   <!-- your select of fonts and other toolbar entries -->
</div>
<ng-quill-editor id="editor-container" ng-model="myModel" modules="{ toolbar: '#toolbar-container' }"></ng-quill-editor>
```

**Comment by jamielovelace** [comment]
Ah I see, thats exactly what I need, great! 🎉
