### ISSUE TITLE
Issues with form validity and dynamically adding ng-quill to DOM

### ISSUE THREAD

**Issue by rafaelhamasaki** [KillerCodeMonkey/ng-quill#89]
Given the following code, I'd expect the form to turn invalid as soon as I click the "Add Item" button, thus disabling the "Submit" button. However, the "Submit" button stays enabled. ng-quill version is **2.2.3**.

```
<form name="form" ng-submit="$ctrl.submit()">
  <button ng-click="$ctrl.addItem()">Add Item</button>
  <!--
    In controller:
    addItem() {
      this.items.push({});
    }
  -->

  <div ng-repeat="item in $ctrl.items">
    <ng-quill-editor ng-model="item.description" min-length="1"></ng-quill-editor>
  </div>
	
  <button type="submit" ng-disabled="form.$invalid">Submit</button>
</form>
```

**Comment by KillerCodeMonkey** [comment]
hey there,

i checked this and i do not have this problem.

I added a simple example to the demo.html --> check out the last ng-quill-editor there:
http://killercodemonkey.github.io/ng-quill/demo.html

**Comment by rafaelhamasaki** [comment]
In your demo, the ng-quill editor is not added dynamically to the DOM.

Please see the following codepen:
[http://codepen.io/anon/pen/Lxgzgd](http://codepen.io/anon/pen/Lxgzgd)

**Comment by rafaelhamasaki** [comment]
I figured out that my problem actually has nothing to do with dynamically adding the editor to the DOM. I should have use the "required" attribute in the ng-quill-editor component to achieve what I want. I assumed that it wouldn't work because it's not documented, so I resorted to min-length="1" instead.

The source of my confusion was that the min-length validation was triggered when I typed into the editor and deleted it's content afterwards, so I thought that it was some kind of component initialization issue.

I began writing a codepen comparing ng-quill's min-length with ng-minlength, and realized that ng-minlength only works with a non-empty model, so ng-quill is somewhat in line with that. I say "somewhat" because a ng-quill-editor instance with min-length validation is considered invalid when text is typed and then deleted. This is different to how Angular's ng-minlength behaves: To ng-minlength, an empty model is considered valid, regardless if dirty or not.

Open the following codepen and delete the contents from the editor and from the input text to see the different behaviors:

http://codepen.io/anon/pen/YNJEMP

**Comment by KillerCodeMonkey** [comment]
so what do you expect? should min-length should not be triggered if empty?

You can decide, if i need to change something ;)

**Comment by rafaelhamasaki** [comment]
I personally would strive to keep behavior as close as possible to vanilla Angular, so I would make min-length not trigger when the editor model is empty.

But you're the creator of this component, so it's up to what you feel makes more sense really. :)

**Comment by KillerCodeMonkey** [comment]
released a new version:

https://killercodemonkey.github.io/ng-quill/demo.html

check it out. if your editor is empty min-length is valid and required is invalid.
