### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chaituGS** [KillerCodeMonkey/ng-quill#91]
its not working with METEOR, don't know what's the issue is..

**Comment by KillerCodeMonkey** [comment]
any further information like, what you have tried, how do you include it and so on? if not i will close this issue immediately. ;)

**Comment by chaituGS** [comment]
it was working earlier, but suddenly we don't know what happened its not working in our production environment, but working in our local

**Comment by KillerCodeMonkey** [comment]
dude... more infos... which ngquill/quill version are you using local and which in production.

Maybe you are using quill 0.2.x locally and on production you installed 2.x or something like that.

**Comment by chaituGS** [comment]
using  2.1.0 at both the places

**Comment by KillerCodeMonkey** [comment]
Maaaan give me some insights... 

JS errors on production... if .. show me the error messages or something.

If it works locally .. you did something wrong on the production system... so not my fault...
I give you a last chance to provide some relevant data... if not: Good luck to fix your prod system ;)

**Comment by chaituGS** [comment]
15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:59 TypeError: this.observer.takeRecords is not a function
    at t.optimize (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:13)
    at t.y (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:19)
    at new t (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:19)
    at Object.n [as create] (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:13)
    at new e (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:13)
    at n.component.controller.$postLink (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:98)
    at 15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:58
    at i (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:57)
    at h (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:58)
    at a (15cf0f1b540434bac1f0a117b554c9eb7fd3140c.js:58)

**Comment by chaituGS** [comment]
This is the error i am getting in my production env

**Comment by KillerCodeMonkey** [comment]
congratulation ... an error message of an bundled and hopefully minified js-file *applause 

Maybe your buildprocess destroys something.

If you run the project locally you are using the not bundled/minified scripts?

**Comment by chaituGS** [comment]
I DONT HAVE ANY FURTHER INFORMATION REGARDING THIS

**Comment by KillerCodeMonkey** [comment]
yeah then sorry... i do not know anything about your prod system or your buildprocess... and maybe someone should open issues ans ask question, who has those information...

bye

**Comment by cmitcoe** [comment]
@KillerCodeMonkey We are using ng-quill 2.1.0 in our meteor app. 

And the error we are getting is as below. This is the only error I can show you now. 

![ngquill1](https://cloud.githubusercontent.com/assets/25744751/22885591/0e6e9dfe-f220-11e6-9408-cd5b7298acbb.PNG)


In the UI we should see the text editor and that's not coming. Please see below screenshot.

![ngquill](https://cloud.githubusercontent.com/assets/25744751/22885617/2bb2ee74-f220-11e6-9795-3fc83ed576d0.PNG)


Hope this information can help you figure out something about the issue and help here.

**Comment by KillerCodeMonkey** [comment]
Could you paste the source code of the controller/component?

**Comment by Frankwalraven** [comment]
@KillerCodeMonkey 
They have to answer from India, So it will become in all probability tomorrow morning.
I apologize for the way in how the issue was reported.
Thank you for your time

**Comment by cmitcoe** [comment]
Hi @KillerCodeMonkey 

I am opening a new thread with more details on the issue. 

Thank You.
