### ISSUE TITLE
ng-attr-title not working on select tags with ng-quill and a custom toolbar?

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ng-quill#94]
but is working with vanilla quill and a custom toolbar...

Hover over Bold on each. ng-attr title works.
Hover over Alignment, it uses ng-attr-title and is only working with vanilla quill.
Hover over Alignment2, it uses a regular title and works on both.

http://jsbin.com/yumifabexa/edit?html,js,output

**Comment by KillerCodeMonkey** [comment]
hehe, nice catch... lols ^^. strange thing here. Could not expect what happens here.

i will check this. feel free to add a pull request, if you solved this earlier

**Comment by KillerCodeMonkey** [comment]
The problem is, that I create the editor in the $postLink callback.

If you wrap the creation of the vanilla quill in `this.$postLink` function the ng-attr-title is not working either. 

Strange. So i will check, if ng-quill is also working in $onInit hook instead of $postLink.. but $postLink would be the better choice..

EDIT: ng-quill works in $onInit but the dynamic title not. i think this is a timing issue, because if you inspect the dom --> the title is correct set to select-box, but not for the overlay-span.

Strange, seems like the overlay of the selects are outside of angular context Oo

**Comment by KillerCodeMonkey** [comment]
Yep, like i thought.

1. add an ng-if to ng-quill-component node
2. set the condition to true --> wrapped in a simple timeout
3. title works

**Comment by jziggas** [comment]
That is very strange indeed. I'll try to look at this more over the weekend. We have language translations to consider, so everything needs to be interpolated ( e.g. `ng-attr-title="{{'Alignment' | translate}}"`) which is why I found this issue. I think you're right about the timing issue though, because I have this other nasty bug where the toolbar buttons don't get rendered correctly and it seems like it is because the editor is wrapped in some complex ngIf/ngRepeat logic.

There's also something else weird happening where I tried to give the toolbar a randomized ID because of multiple instances of the editor on the screen (e.g. `id="toolbar-container-{{rand(1000)}}"`) but it started throwing a bunch of errors. Could be another timing issue or something unrelated. Haven't opened any other issues here yet because of the confusing nature of the bugs and it's hard to tell if some of the problems are with my code base or quill/ng-quill. Anyway thanks for doing some initial testing.

**Comment by jziggas** [comment]
Here is an example where `ng-attr-id` also does not work: http://jsbin.com/bitupirewu/edit?html,js,console,output

The use case for this is to provide a unique ID for each toolbar when there are multiple editors on the screen.

**Comment by KillerCodeMonkey** [comment]
Hey there i have spent some hours today and tested your solution --> $scope.$applyAsync was to early, even $scope.$evalAsync was to fast. So i ended up what i did at the beginning of ng-quill *sadly --> $timeout, we have to wait until the dom is rendered.

For better usage you can add the toolbar as ngTransclude with the element --> ng-quill-toolbar.
So this will handle to hide everything until the editor is created correctly, to avoid flickering effects of seeing the original toolbar-content and the final one of the quill instance.

the readme and demo page is up to date.

Thanks for your help! i appreciate your work and feel free to add other features if you think, you need them.
