### ISSUE TITLE
How to configure toolbar items?

### ISSUE THREAD

**Issue by Louis-C** [KillerCodeMonkey/ng-quill#96]
I'm new to ng-quill and want to know how to configure the editor's toolbar items.
I found some instructions on [http://ngmodules.org/modules/ngQuill](http://ngmodules.org/modules/ngQuill) and thought I can use `toolbar` attribute and `toolbar-entries` as stated but the result is different from I expected:

![screenshot from 2017-02-18 17 05 21](https://cloud.githubusercontent.com/assets/9493876/23091989/a18b0fde-f5fc-11e6-9158-bfa6d738daa3.png)

Am I using the directive in a wrong way? I was expecting either the toolbar got hidden or the toolbar items got set according to the value (or both)

You may refer to [https://codepen.io/louiscth/pen/bgyKMB](https://codepen.io/louiscth/pen/bgyKMB)
BTW, My runtime environment is Ubuntu 14.04 with Chrome Version 56.0.2924.87

**Comment by KillerCodeMonkey** [comment]
naaaa ngmodules is crappy --> read the readme here ;). There is no toolbar-entries any longer in the new version.
https://github.com/KillerCodeMonkey/ng-quill/blob/develop/README.md

the default toolbar configuration looks like this:
```
modules: {
    toolbar: [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block'],

        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction

        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
        [{ 'align': [] }],

        ['clean'],                                         // remove formatting button

        ['link', 'image', 'video']                         // link and image, video
    ]
}
```

and you can pass modules-config object to the ng-quill-editor component --> it is explained in the readme. and there is a `demo.html` in the root of this repo, with some usage examples.

you can even build your own toolbar following the guides on quilljs:
http://quilljs.com/playground/#custom-fonts

simply pass something like this as module config `{ toolbar: '#IDofMyToolbarElement' }`.

Please close the issue on your own, if this helps and you get it, Thanks.

**Comment by Louis-C** [comment]
Thank you for pointing me that the `toolbar-entries` no longer exists.

By passing the module config as you suggested, I can now reference the toolbar to the DOM.

I've seen in [https://killercodemonkey.github.io/ng-quill/demo.html](https://killercodemonkey.github.io/ng-quill/demo.html) how you control the 'read-only' status , so I expected the `toolbar` attribute should be the same (since in the readme, there is a line

- show toolbar: toolbar="isVisible" (default: false)

My goal is to show/hide the toolbar on the fly, so I copied the way you use to set read-only in my 2nd editor,
![capture](https://cloud.githubusercontent.com/assets/9493876/23092840/98745ac4-f60e-11e6-89f9-865d11a73851.PNG)

The 'toggle readOnly' function works just fine as in the demo page, but 'toggle visibility' button doesn't do anything for me. I can of course hide the toolbar by using ng-hide in the toolbar container DOM like what I did with the 1st editor, but I thought I can use toolbar="xxx" directly... Would you mind giving me some suggestion on the `toolbar` usage?

I've created another codepen just for reference:
[https://codepen.io/louiscth/pen/PWvBBE](https://codepen.io/louiscth/pen/PWvBBE)

Thanks.

**Comment by KillerCodeMonkey** [comment]
there is not toolbar option in the newer ngquill version, just an invalid readme sorry ;)
just disable the toobar via modules config if the editor is initialized.

There was no need toggle toolbar on the fly.

**Comment by KillerCodeMonkey** [comment]
I released a new version an updated the readme. sorry for the confusion.
