### ISSUE TITLE
How to access ng-quill controller from ng-quill-toolbar?

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ng-quill#97]
For multiple editor instances in the browser it is necessary to give each custom toolbar a unique ID. In my case, I've created a component which wraps ng-quill and generates a UUID automatically, such that in my `component.js`:

```
controller: () {
  ...
  vm.toolbarId = generateUUID();
  ...
}
```

And in my `component.html` I'm trying to achieve something like:

```
<ng-quill modules="vm.myModules" ng-model="vm.myContent">
    <ng-quill-toolbar ng-attr-id="{{vm.toolbarId}}">
        <span class="ql-formats">...</span>
    <ng-quill-toolbar>
</ng-quill>
```

However it is my understanding that a transcluded element has an isolated child scope of the parent component. So you can't simply say `vm.toolbarId`. Maybe it is something like `$parent.$parent.toolbarId` but I'm not sure. Any suggestions?

**Comment by jziggas** [comment]
Ohhhh it looks like you are already taking care of this with:

```
if ($transclude.isSlotFilled('toolbar')) {
    config.modules.toolbar = container.find('ng-quill-toolbar').children()[0];
}
```

by providing the DOM node rather than an ID. Ha, ok. I will close this.

**Comment by KillerCodeMonkey** [comment]
but event ```ng-attr-id="{{vm.toolbarId}}"``` should work. the transcluded child scope is not isolated i think per default. because the intention of transclude is to leave also the databinding to the outer scope.

but yeah, i am using transclusion to avoid the ugly need of passing a unique css-selector for quill creation.

**Comment by jziggas** [comment]
Yeah that wasn't working for me for some reason. I would just get `id="{{vm.toolbarId}}"`. But if I did something like `ng-attr-id="{{'test-string'}}"` I would correctly get `id="test-string"`. But I removed my fancy ID logic once I read your source since it was no longer necessary. IDK.

**Comment by KillerCodeMonkey** [comment]
maybe you should have use `$ctrl.toolbarId`? You are using `vm` as `this` in your component controllers, but the default controllerAs is `$ctrl` ;)

**Comment by jziggas** [comment]
We follow the John Papa Angular style guide and use controllerAs syntax in our components, so that's not an issue because we declare `controllerAs: 'vm'` in our component bindings.

**Comment by KillerCodeMonkey** [comment]
okay, strange, well then. The new provided way without ids should be better.. nevermind.

**Comment by jziggas** [comment]
Yeah it's a lot nicer not having to think about it, so thanks for that quick version update!
