### ISSUE TITLE
using Multiple directives, asking for new/isolated scope

### ISSUE THREAD

**Issue by winsandymyint** [KillerCodeMonkey/ng-quill#99]
Hi  @KillerCodeMonkey , 
When I use **[ment.io](https://github.com/jeff-collins/ment.io)** directive combine with ng-quill, it keep showing me the following error. Could you show the way how to solve it? 

```
<ng-quill-editor ng-model="user.description" msd-elastic="1"
mentio
mentio-typed-text="typedTerm"
mentio-items="user.current | filter:username:typedTerm"
mentio-select="user.selected(item)"
mentio-menu-position="'top'">
</ng-quill-editor>
```

![multiple directive](https://cloud.githubusercontent.com/assets/2322490/23396248/4a0d2158-fdc1-11e6-9ef0-b8a230d09e36.jpg)

**Comment by KillerCodeMonkey** [comment]
yeah i think this will not work. both are directives/components with isolated scope an the same element.

i do not know much about mentio and how it works. 

But you could try the following:
add a hidden input with the same ngmodel as the ng-quill editor has + the mentio directives

But i think then, the list of users will be not positionated correctly.

**Comment by KillerCodeMonkey** [comment]
or you add your own little directive without isolated scope --> with ng-quill you get informed if the model changed, and with the editor instance you can get cursor position --> a little regex listening on `@` and so on. For details you can simply look in the mentio repo.

**Comment by winsandymyint** [comment]
I get it. Thank you for your help. 👍

**Comment by KillerCodeMonkey** [comment]
nice, but could you post your solution?

**Comment by winsandymyint** [comment]
sure, I will.

**Comment by winsandymyint** [comment]
I tried to write my own directive for a couple of hr. It didn't work well. And now I used the trickiest way as you said before, used the same model. 😝 
```
<input 
	type="hidden" 
	name="users"
	class="input-mention hidden" 
	ng-model="user.description" 
	mentio
	mentio-typed-text="typedTerm"
	mentio-items="user.current | filter:username:typedTerm"
	mentio-select="user.selected(item)"
	mentio-menu-position="'top'"

/>

<ng-quill-editor 
	ng-model="user.description" 
	msd-elastic="1"
>
</ng-quill-editor>
```
Check result below.
<img width="393" alt="screen shot 2017-03-01 at 4 40 42 pm" src="https://cloud.githubusercontent.com/assets/2322490/23455406/e1d1f0cc-fe9d-11e6-9ecd-fb96bca7f887.png">

Thanks @KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
lols^^ ... did not expect this, but nice!
